<a href="https://colab.research.google.com/github/Nisfah0706/A11.2025.15915_PMesin/blob/main/memuat_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!pip install pandas
!pip install numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [5]:
# import library
import pandas as pd
import numpy as np

In [6]:
# load dataset
path = "epl-goalscorer(20-21).csv"
df = pd.read_csv(path)

FileNotFoundError: [Errno 2] No such file or directory: 'epl-goalscorer(20-21).csv'

In [7]:
import os
print(os.getcwd())
print(os.listdir())

/content
['.config', 'sample_data']

In [8]:
from google.colab import files
files.upload()

Saving epl-goalScorer(20-21).csv to epl-goalScorer(20-21).csv

{'epl-goalScorer(20-21).csv': b',id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup\n0,647,Harry Kane,35,3097,23,22.174858909100294,14,7.577093588188291,138,49,1,0,F,Tottenham,19,19.130183439701796,24.995648321695626,4.451256847940385\n1,1250,Mohamed Salah,37,3085,22,20.250846637412906,5,6.528526101261377,126,55,0,0,F M S,Liverpool,16,15.683833638206124,28.968233548104763,9.800235655158758\n2,1228,Bruno Fernandes,37,3117,18,16.0194544615224,12,11.474995978176594,121,95,6,0,M S,Manchester United,9,8.40783962700516,26.911412378773093,11.93228487111628\n3,453,Son Heung-Min,37,3139,17,11.023286756128073,10,9.512992469593883,68,75,0,0,F M S,Tottenham,16,10.26211790367961,20.6719155497849,6.608751138672233\n4,822,Patrick Bamford,38,3085,17,18.401862610131502,7,3.7822465524077415,107,30,3,0,F S,Leeds,15,16.87952494621277,23.394952706992626,4.131795546039939\n5,5555,Dominic Calvert-Lewin,32,2788,16,18.136448714882135,0,2.101818833500147,82,18,3,0,F S,Everton,16,18.136448714882135,19.69885002076626,4.159406214952469\n6,755,Jamie Vardy,34,2848,15,19.94294610992074,9,5.087881522253156,82,28,1,0,F S,Leicester,7,13.0924265794456,18.227907367050648,2.41258773393929\n7,8865,Ollie Watkins,37,3330,14,16.280177645385265,5,5.314029491506517,98,45,2,1,F,Aston Villa,13,14.757840014994144,22.014020785689354,5.3349911738187075\n8,314,Ilkay G\xc3\xbcndogan,28,2033,13,9.566883080638945,2,3.8162196557968855,54,42,1,0,M S,Manchester City,12,8.044545345939696,19.286811731755733,10.148374736309052\n9,3277,Alexandre Lacazette,30,1928,13,12.028909418731928,2,2.209213115274906,45,22,3,0,F M S,Arsenal,10,9.745402876287699,14.361542394384742,2.9379407837986946\n10,468,Callum Wilson,26,2079,12,13.59009125083685,5,3.046300631016493,49,17,2,0,F S,Newcastle United,8,10.545415870845318,14.205592930316925,1.0525451973080635\n11,620,Kelechi Iheanacho,25,1452,12,9.048596148379147,2,3.534099193289876,59,28,1,0,F S,Leicester,12,8.287427310831845,13.961563635617495,3.4299153089523315\n12,986,Danny Ings,28,2115,12,8.139229241758585,4,2.3112305803224444,56,22,1,0,F S,Southampton,10,6.616891518235207,9.92908869124949,2.0632555447518826\n13,4456,Chris Wood,32,2675,12,12.896009117364883,3,2.03811838850379,69,23,0,0,F S,Burnley,10,11.373671382665634,13.585281524807215,2.1498517598956823\n14,522,Wilfried Zaha,30,2615,11,8.804439894855022,2,3.7028211038559675,60,30,6,0,F M S,Crystal Palace,9,7.282102234661579,13.579472474753857,3.6344361882656813\n15,556,Marcus Rashford,37,2941,11,9.579709991812706,9,4.185122115537524,79,44,4,0,F M S,Manchester United,11,9.579709991812706,20.441910162568092,8.927207557484508\n16,838,Sadio Man\xc3\xa9,35,2805,11,14.828547755256295,7,7.787754854187369,94,61,3,0,F M S,Liverpool,11,14.828547755256295,24.99892319738865,6.057656282559037\n17,2251,Gareth Bale,20,909,11,5.797857677564025,2,1.842241395264864,38,21,1,0,M S,Tottenham,11,5.797857677564025,8.149640910327435,2.5945137250237167\n18,7153,Matheus Pereira,33,2594,11,6.948316538706422,6,6.355539299547672,65,58,2,1,M S,West Bromwich Albion,7,3.9036410860717297,10.857054157182574,3.75792377255857\n19,318,Pierre-Emerick Aubameyang,28,2254,10,10.194088630378246,3,2.3524065418168902,55,19,2,0,F M S,Arsenal,8,8.671750970184803,14.778997933492064,3.955129318870604\n20,531,Michail Antonio,25,1923,10,14.138838540762663,5,3.0349448639899492,63,25,3,0,F S,West Ham,10,14.138838540762663,18.99889111146331,2.6550637893378735\n21,606,Christian Benteke,30,1824,10,7.457401188090444,1,0.6976262861862779,71,15,1,1,F S,Crystal Palace,10,7.457401188090444,8.47283953242004,3.153553775511682\n22,618,Raheem Sterling,30,2449,10,11.763264082372189,6,5.817095670849085,68,35,3,0,F M S,Manchester City,10,11.002095226198435,24.088666174560785,11.477124504745007\n23,3294,Edinson Cavani,26,1355,10,8.603231720626354,3,2.3172435145825148,34,14,4,0,F S,Manchester United,10,8.603231720626354,12.259187385439873,2.730645166710019\n24,5612,Anwar El Ghazi,28,1612,10,9.037517840974033,0,1.8828656133264303,64,26,2,0,F M S,Aston Villa,6,5.99284244235605,7.845562790520489,2.6913463715463877\n25,8288,Tomas Soucek,37,3330,10,8.936489820480347,1,2.3296639565378428,63,17,7,1,M,West Ham,10,8.936489820480347,16.730339899659157,8.610449083149433\n26,482,Roberto Firmino,36,2882,9,12.860213406383991,7,6.116863399744034,83,44,2,0,F M S,Liverpool,9,12.860213406383991,25.271457761526108,10.198550110682845\n27,558,Jesse Lingard,15,1344,9,5.095250342041254,4,2.329288413748145,39,18,3,0,F M,West Ham,8,3.5729127153754234,9.868648286908865,5.617282949388027\n28,750,Riyad Mahrez,26,1894,9,6.151045539416373,5,5.954979481175542,56,43,0,0,F M S,Manchester City,9,6.151045539416373,18.641167933121324,9.019599789753556\n29,6681,Harvey Barnes,25,1954,9,6.697319919243455,4,1.7716880273073912,56,26,0,0,F M S,Leicester,9,6.697319919243455,8.893774410709739,1.5948405284434557\n30,6854,Diogo Jota,19,1114,9,7.05772053822875,0,1.7625210750848055,46,12,2,0,F M S,Liverpool,9,7.05772053822875,10.972974702715874,4.0760964918881655\n31,7700,Che Adams,36,2685,9,12.118734162300825,5,5.227753505110741,55,37,1,0,F S,Southampton,9,12.118734162300825,14.486911714076996,2.7446243297308683\n32,843,James Ward-Prowse,37,3330,8,5.427161182276905,7,3.9566464591771364,42,57,5,0,D M,Southampton,5,2.3824858171865344,10.150620041415095,8.928798945620656\n33,1776,Jarrod Bowen,37,2514,8,7.817085841670632,5,4.952177892439067,53,28,0,0,F M S,West Ham,8,7.817085841670632,14.000130595639348,3.0969949951395392\n34,3621,Neal Maupay,33,2526,8,13.773534506559372,2,4.277407880872488,71,32,1,1,F M S,Brighton,5,10.728932749480009,17.157539159059525,3.381784765049815\n35,5543,Gabriel Jesus,28,1977,8,9.009614009410143,4,3.37188967410475,52,29,2,0,F M S,Manchester City,8,9.009614009410143,16.564743790775537,5.563634850084782\n36,5656,Nicolas Pepe,28,1512,8,5.811174319125712,1,1.0121600376442075,43,11,1,1,F M S,Arsenal,7,5.050005499273539,9.170708017423749,4.217725777998567\n37,6055,Phil Foden,27,1548,8,5.43758063390851,5,4.749281365424395,43,36,0,0,F M S,Manchester City,8,5.43758063390851,13.111076783388853,5.408362489193678\n38,6630,Joe Willock,21,1215,8,5.088089782744646,0,0.7337011601775885,23,10,1,0,M S,"Arsenal,Newcastle United",8,4.326921004801989,7.0070693753659725,2.9877271251752973\n39,6818,James Maddison,31,2123,8,3.827569866552949,5,5.386723920702934,75,50,4,0,M S,Leicester,8,3.827569866552949,11.743431102484465,6.073130352422595\n40,8718,Stuart Dallas,38,3412,8,4.457073524594307,2,2.084683418273926,48,26,7,0,D M,Leeds,8,4.457073524594307,18.534343764185905,13.809802262112498\n41,8720,Jack Harrison,36,2871,8,6.254042700864375,8,7.5230593085289,46,59,2,0,M S,Leeds,8,6.254042700864375,19.39748965576291,8.035575423389673\n42,695,Bertrand Traor\xc3\xa9,36,2362,7,6.304105126298964,6,4.570987721905112,64,35,1,0,F M S,Aston Villa,7,6.304105126298964,9.835355166345835,1.3322140527889132\n43,1389,Jorginho,28,2022,7,6.972690678201616,1,1.954869382083416,14,24,2,0,M S,Chelsea,0,0.12224532943218946,11.383730475790799,10.87897537369281\n44,2381,Rodrigo,26,1285,7,5.755642192438245,2,3.200529370456934,46,31,3,0,F M S,Leeds,7,5.755642192438245,10.81597439199686,4.3486531134694815\n45,6026,Richarlison,33,2803,7,10.427271598950028,3,3.3947611711919308,78,25,3,1,F M S,Everton,6,9.666102761402726,15.678682796657085,5.1744528617709875\n46,6441,Ferr\xc3\xa1n Torres,23,1291,7,5.7287076292559505,2,2.202425992116332,36,18,1,0,F M S,Manchester City,7,5.7287076292559505,9.768890779465437,2.7242567520588636\n47,7490,Mason Greenwood,31,1825,7,6.975748036056757,2,2.4278998095542192,67,14,2,0,F M S,Manchester United,7,6.975748036056757,14.031832756474614,5.954058945178986\n48,7711,David McGoldrick,34,2319,7,7.383083622902632,1,1.050453633069992,65,16,7,0,F M S,Sheffield United,7,7.383083622902632,9.68200909346342,3.1875317404046655\n49,65,Timo Werner,35,2605,6,13.432795586064458,8,6.66727664321661,80,36,2,0,F M S,Chelsea,6,13.432795586064458,20.533462934195995,5.242121719755232\n50,501,Danny Welbeck,24,1551,6,7.380381532013416,1,3.231366850435734,35,22,0,0,F M S,Brighton,6,6.6192494705319405,10.265666516497731,1.476512636989355\n51,675,Jack Grealish,26,2187,6,5.192683823406696,10,9.334136627614498,50,81,5,0,F M S,Aston Villa,6,5.192683823406696,17.48746880888939,6.972043983638287\n52,702,Tammy Abraham,22,1027,6,6.189150683581829,1,0.7214874606579542,32,9,0,0,F S,Chelsea,6,6.189150683581829,7.9011704083532095,2.1223282255232334\n53,714,Gylfi Sigurdsson,35,2189,6,5.62011415604502,5,4.763620866462588,46,43,2,0,F M S,Everton,3,3.3366075986996293,8.377620616927743,3.660514172166586\n54,2249,James Rodr\xc3\xadguez,23,1802,6,3.3635378424078226,4,5.439711567014456,37,40,4,0,F M S,Everton,6,3.3635378424078226,12.033004865050316,7.104181377217174\n55,5956,Youri Tielemans,38,3359,6,4.168203926645219,4,3.312251338735223,48,49,6,0,M S,Leicester,4,2.6458663111552596,18.97534204274416,14.94546852633357\n56,7768,Mason Mount,36,2891,6,6.884880336001515,5,9.847691355273128,82,87,2,0,F M S,Chelsea,5,6.123711509630084,21.69607448298484,12.443149040453136\n57,8026,Raphinha,30,2369,6,6.219142843037844,9,9.524860586971045,67,65,3,0,M S,Leeds,6,6.219142843037844,16.792777836322784,6.679691860452294\n58,447,Kevin De Bruyne,24,1918,5,9.908439546823502,11,10.00376264937222,79,72,1,0,M S,Manchester City,3,7.624932937324047,21.079131573438644,10.636447556316853\n59,935,Kurt Zouma,24,2024,5,3.1368534453213215,0,0.08146697096526623,27,4,3,0,D S,Chelsea,5,3.1368534453213215,6.216146335937083,6.133133308030665\n60,4476,Callum Robinson,28,1580,5,3.2030633985996246,0,1.0499632060527802,31,16,0,0,F M S,West Bromwich Albion,5,3.2030633985996246,5.2165407538414,1.5963355377316475\n61,6048,Lewis Dunk,32,2844,5,2.6992577090859413,0,0.830638368614018,31,10,5,2,D,Brighton,5,2.6992577090859413,8.265677943825722,7.870708651840687\n62,6382,Pedro Neto,31,2570,5,5.494995640590787,6,5.738268097862601,62,61,4,0,F M S,Wolverhampton Wanderers,5,5.494995640590787,11.516661681234837,4.206935252994299\n63,6827,Bobby Reid,33,2394,5,4.269851532764733,2,1.3097007106989622,34,14,7,0,D F M S,Fulham,5,4.269851532764733,8.202645358629525,3.1313844807446003\n64,6853,R\xc3\xbaben Neves,35,2591,5,4.715056136250496,1,2.002833073027432,65,32,7,0,M S,Wolverhampton Wanderers,2,2.4315496180206537,6.769231723621488,4.476360370405018\n65,7322,Bukayo Saka,31,2561,5,7.169173587113619,3,4.511790654622018,61,38,1,0,D F M S,Arsenal,5,7.169173587113619,18.292466390877962,9.180439569987357\n66,7698,Leandro Trossard,34,2601,5,5.412756389006972,5,5.398416234180331,58,51,2,0,F M S,Brighton,5,5.412756389006972,15.99893451668322,7.631562136113644\n67,87,Joelinton,31,2006,4,5.631002204492688,2,2.366481453180313,43,17,3,0,F M S,Newcastle United,3,4.869833366945386,9.268310604617,3.2849576491862535\n68,502,Olivier Giroud,17,750,4,5.070415806025267,0,1.1757991276681423,29,6,1,0,F S,Chelsea,4,5.070415806025267,5.245491370558739,1.7113372217863798\n69,553,Anthony Martial,22,1494,4,7.405651165172458,3,2.6198029601946473,42,17,0,1,F M S,Manchester United,4,7.405651165172458,11.814813017845154,3.3195053301751614\n70,586,John Stones,21,1843,4,2.3939535319805145,0,0.04683952126652002,14,2,0,1,D,Manchester City,4,2.3939535319805145,9.842463970184326,9.742794871330261\n71,2662,Christian Pulisic,27,1739,4,6.775412477552891,2,2.7612321693450212,43,25,2,0,F M S,Chelsea,4,6.775412477552891,14.593857947736979,7.101119593717158\n72,4105,Ra\xc3\xbal Jim\xc3\xa9nez,10,824,4,2.3609096854925156,0,0.6329625025391579,26,6,0,0,F,Wolverhampton Wanderers,4,2.3609096854925156,3.6840762607753277,1.2332111839205027\n73,4381,Mateusz Klich,35,2404,4,2.999958790373057,5,3.6508504655212164,36,44,6,0,M S,Leeds,2,1.4776211227290332,14.60811685398221,10.386438000015914\n74,5220,Kai Havertz,27,1523,4,6.352183712646365,3,1.553381915204227,33,18,2,0,F M S,Chelsea,4,6.352183712646365,10.382943627424538,4.811911249533296\n75,5556,Ademola Lookman,34,2765,4,6.251116008497775,4,5.25840737298131,69,61,5,0,F M S,Fulham,4,5.48994714114815,15.355220101773739,7.334159415215254\n76,5560,Scott McTominay,32,2121,4,1.8477440048009157,1,2.11461328715086,26,17,3,0,M S,Manchester United,4,1.8477440048009157,10.912294186651707,7.904809940606356\n77,6893,Stuart Armstrong,32,2701,4,2.5625904174521565,5,2.5180577896535397,51,33,3,0,M S,Southampton,4,2.5625904174521565,9.479516074061394,6.250183904543519\n78,7420,Miguel Almir\xc3\xb3n,34,2458,4,3.509381879121065,1,3.1359253535047174,33,31,3,0,F M S,Newcastle United,4,3.509381879121065,9.295024225488305,3.899067119695246\n79,8706,Eberechi Eze,34,2570,4,2.494572142139077,6,3.741961938329041,37,42,3,0,M S,Crystal Palace,4,2.494572142139077,7.996477495878935,3.959954559803009\n80,8778,Fabio Silva,31,1251,4,5.958538793027401,2,1.0354305505752563,45,10,2,0,F S,Wolverhampton Wanderers,3,5.197369962930679,4.897674456238747,1.0702383313328028\n81,101,Allan Saint-Maximin,25,1578,3,2.8259131088852882,4,4.013324308209121,30,29,0,0,F M S,Newcastle United,3,2.8259131088852882,10.59472032263875,4.22400295548141\n82,111,Jannik Vestergaard,29,2481,3,2.0269474890083075,0,0.7408252637833357,22,7,3,1,D S,Southampton,3,2.0269474890083075,5.853648511692882,5.7788641303777695\n83,239,Pascal Gro\xc3\x9f,33,2379,3,5.010525770485401,8,5.368290125392377,32,69,3,0,D M S,Brighton,0,1.9658871926367283,10.404419407248497,6.732295144349337\n84,503,Theo Walcott,22,1660,3,2.280676642432809,3,1.2631027586758137,29,17,0,0,F M S,"Everton,Southampton",3,2.280676642432809,5.551979407668114,2.2335501089692116\n85,528,Angelo Ogbonna,27,2403,3,1.6960736466571689,0,0.4284707475453615,13,4,5,0,D,West Ham,3,1.6960736466571689,3.929544437676668,3.7070494927465916\n86,592,Ross Barkley,26,1574,3,3.6999339712783694,1,4.31900261156261,39,40,0,0,M S,"Aston Villa,Chelsea",3,3.6999339712783694,9.896902839653194,3.7172514870762825\n87,669,Ashley Westwood,37,3322,3,1.0059903170913458,3,6.3520893305540085,19,49,7,0,M,Burnley,3,1.0059903170913458,10.010638365522027,6.2872747303918\n88,773,Aleksandar Mitrovic,27,1369,3,5.677362998947501,3,2.9247111547738314,59,23,3,0,F S,Fulham,2,4.1550253089517355,7.808299113065004,1.8494821228086948\n89,782,Ben Chilwell,27,2296,3,2.9848903995007277,5,2.455677840858698,27,30,3,0,D M,Chelsea,3,2.9848903995007277,11.330961346626282,8.155131921172142\n90,804,Craig Dawson,21,1835,3,2.6924522039480507,0,0.054468296468257904,15,2,3,1,D,West Ham,3,2.6924522039480507,2.9267580080777407,2.9267580080777407\n91,964,Kyle Bartley,30,2581,3,2.6014003232121468,1,0.7599650248885155,14,7,4,0,D S,West Bromwich Albion,3,2.6014003232121468,2.48464941047132,1.4993401113897562\n92,1017,Matej Vydra,27,1322,3,5.373272832483053,2,2.1183407343924046,35,14,0,0,F S,Burnley,3,5.373272832483053,6.425857454538345,1.0472040101885796\n93,1653,Michael Keane,34,2896,3,1.5046916585415602,1,1.0852528270334005,16,7,4,0,D S,Everton,3,1.5046916585415602,6.840392814949155,6.564230026677251\n94,1740,Paul Pogba,26,1893,3,2.9882028456777334,3,2.066863002255559,31,24,3,0,M S,Manchester United,3,2.9882028456777334,11.6914734095335,7.444205395877361\n95,2335,Pablo Fornals,32,2513,3,5.854254933074117,3,2.0546394819393754,46,28,3,0,F M S,West Ham,3,5.854254933074117,14.868230648338795,8.320599706843495\n96,3293,Lucas Moura,30,1392,3,1.9466326590627432,4,2.0640352852642536,18,16,1,0,F M S,Tottenham,3,1.9466326590627432,7.51403795927763,5.200064562261105\n97,3428,H\xc3\xa9lder Costa,22,1152,3,2.598154854029417,3,0.6283337883651257,16,7,0,0,M S,Leeds,3,2.598154854029417,4.516011323779821,2.2073262743651867\n98,3491,Romain Saiss,26,2319,3,3.099967914633453,0,0.648439958691597,27,4,2,0,D,Wolverhampton Wanderers,3,3.099967914633453,4.53897300362587,3.720982971601188\n99,3683,Ivan Cavaleiro,36,2477,3,5.548666689544916,0,2.68047393579036,47,42,2,0,D F M S,Fulham,2,4.026328969746828,8.240886438637972,2.8567301016300917\n100,4422,Ashley Barnes,21,1341,3,3.874066237360239,0,0.8005475150421262,38,19,4,0,F M S,Burnley,2,3.1128973700106144,4.19031529314816,1.1986291762441397\n101,5587,Josh Maja,15,809,3,4.918053388595581,0,0.7428302690386772,21,7,0,0,F S,Fulham,2,4.156884551048279,4.449021197855473,0.6455439738929272\n102,5595,Daniel James,14,830,3,1.9432968124747276,0,0.7408441361039877,16,7,3,0,M S,Manchester United,3,1.9432968124747276,4.284207716584206,1.735916318371892\n103,5962,Tanguy NDombele Alvaro,33,2141,3,1.5304815424606204,2,2.1263335961848497,18,14,3,0,M S,Tottenham,3,1.5304815424606204,10.934965118765831,8.005785129964352\n104,6144,S\xc3\xa9bastien Haller,16,933,3,2.554668180644512,0,1.134867813438177,25,10,0,0,F S,West Ham,3,2.554668180644512,3.66033024340868,0.8529489319771528\n105,7712,Billy Sharp,16,723,3,2.983076898381114,0,0.5832782126963139,9,4,1,0,F S,Sheffield United,1,1.4607392232865095,2.650699468329549,0.6648953501135111\n106,7723,John McGinn,37,3330,3,2.166595253162086,5,3.5017576599493623,45,42,12,0,M,Aston Villa,3,2.166595253162086,14.868267310783267,9.945619264617562\n107,8239,Takumi Minamino,18,941,3,2.557263044640422,0,0.7625150121748447,18,4,1,0,F M S,"Liverpool,Southampton",3,2.557263044640422,5.954795576632023,2.767797449603677\n108,8291,Daniel Podence,24,1718,3,2.744377875700593,2,1.8394327834248543,32,21,3,0,F M S,Wolverhampton Wanderers,3,2.744377875700593,6.725102685391903,2.910881344228983\n109,9290,Mbaye Diagne,16,1205,3,6.247825153172016,2,0.9861007407307625,25,10,2,0,F S,West Bromwich Albion,3,6.247825153172016,8.729950740933418,1.773010155186057\n110,343,Pierre-Emile H\xc3\xb8jbjerg,38,3420,2,1.1379272593185306,4,1.7558950493112206,14,16,9,0,M,Tottenham,2,1.1379272593185306,16.20580850355327,14.680379221215844\n111,619,Sergio Ag\xc3\xbcero,11,533,2,3.0022155456244946,1,1.315659787505865,15,7,0,0,F M S,Manchester City,1,1.4798778621479869,3.3636604510247707,1.1454504542052746\n112,725,Ola Aina,31,2683,2,0.8479764661751688,1,1.5527279656380415,14,15,3,0,D M,Fulham,2,0.8479764661751688,6.773145352024585,6.1204672530293465\n113,757,Jeffrey Schlupp,27,1424,2,2.0151155441999435,3,2.5725825037807226,18,18,3,0,M S,Crystal Palace,2,2.0151155441999435,5.158029245212674,3.4669567365199327\n114,766,Jamaal Lascelles,19,1633,2,0.7653548326343298,0,0.06688277795910835,16,2,4,0,D,Newcastle United,2,0.7653548326343298,2.606449857354164,2.349907726049423\n115,770,Ayoze P\xc3\xa9rez,25,1326,2,4.0365753173828125,1,1.2486064918339252,31,23,2,0,F M S,Leicester,2,4.0365753173828125,9.872759373858571,6.759955797344446\n116,771,Georginio Wijnaldum,38,2961,2,2.817426797002554,0,1.6629218505695462,31,21,1,0,M S,Liverpool,2,2.817426797002554,13.922181812115014,10.476276839151978\n117,790,Nathan Redmond,28,1628,2,3.793102962896228,3,2.987433794885874,44,22,1,0,F M S,Southampton,2,3.793102962896228,8.591277278959751,3.1825931146740913\n118,807,Jonny Evans,28,2483,2,1.8557127667590976,2,0.5386310797184706,8,10,7,0,D,Leicester,2,1.8557127667590976,8.730609510093927,7.94296670332551\n119,900,Adama Traor\xc3\xa9,36,2604,2,1.9952622447162867,2,5.228081337176263,41,54,4,0,D F M S,Wolverhampton Wanderers,2,1.9952622447162867,9.37314157281071,3.006398070603609\n120,1024,Tyrone Mings,36,3194,2,2.0616126153618097,2,0.376271465793252,19,7,4,1,D,Aston Villa,2,2.0616126153618097,6.932438758201897,6.708538291044533\n121,1621,Marcos Alonso,13,962,2,1.8240782842040062,0,1.7216993779875338,22,15,2,0,D S,Chelsea,2,1.8240782842040062,4.643395733088255,2.536423623561859\n122,1654,Ben Mee,30,2695,2,1.6194155449047685,0,0.8052035262808204,22,7,3,0,D,Burnley,2,1.6194155449047685,2.1182815926149487,2.01590633392334\n123,1663,Johann Berg Gudmundsson,21,1279,2,1.5160467196255922,0,0.9595043435692787,18,10,2,0,M S,Burnley,2,1.5160467196255922,3.5963619016110897,1.3255044473335147\n124,1678,Michy Batshuayi,18,706,2,1.3631451642140746,1,1.6547212526202202,12,9,0,0,F S,Crystal Palace,2,1.3631451642140746,3.708006873726845,1.4757320675998926\n125,1687,Harry Maguire,34,3049,2,1.4843367198482156,1,0.2909430041909218,36,7,11,0,D,Manchester United,2,1.4843367198482156,13.127003896981478,13.018347103148699\n126,1726,Abdoulaye Doucou

In [12]:
import os
print(os.listdir())

['.config', 'epl-goalScorer(20-21).csv', 'sample_data']

In [14]:
# load dataset
path = "epl-goalScorer(20-21).csv"
df = pd.read_csv(path)

In [15]:
# menampilkan 5 baris awal dari dataset
df.head()

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,0,647,Harry Kane,35,3097,23,22.174859,14,7.577094,138,49,1,0,F,Tottenham,19,19.130183,24.995648,4.451257
1,1,1250,Mohamed Salah,37,3085,22,20.250847,5,6.528526,126,55,0,0,F M S,Liverpool,16,15.683834,28.968234,9.800236
2,2,1228,Bruno Fernandes,37,3117,18,16.019454,12,11.474996,121,95,6,0,M S,Manchester United,9,8.407840,26.911412,11.932285
3,3,453,Son Heung-Min,37,3139,17,11.023287,10,9.512992,68,75,0,0,F M S,Tottenham,16,10.262118,20.671916,6.608751
4,4,822,Patrick Bamford,38,3085,17,18.401863,7,3.782247,107,30,3,0,F S,Leeds,15,16.879525,23.394953,4.131796

In [16]:
# menampilkan 5 baris akhir dari dataset
df.tail()

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
517,517,9415,Jaden Philogene-Bidace,1,1,0,0.000000,0,0.0,0,0,0,0,S,Aston Villa,0,0.000000,0.056044,0.056044
518,518,9423,Gaetano Berardi,2,113,0,0.074761,0,0.0,1,0,0,0,D S,Leeds,0,0.074761,0.231278,0.231278
519,519,9524,Anthony Elanga,1,67,0,0.000000,0,0.0,0,0,0,0,M,Manchester United,0,0.000000,0.000000,0.000000
520,520,9540,Femi Seriki,1,1,0,0.000000,0,0.0,0,0,0,0,S,Sheffield United,0,0.000000,0.000000,0.000000
521,521,9552,Tyrese Francois,1,13,0,0.000000,0,0.0,0,0,0,0,S,Fulham,0,0.000000,0.000000,0.000000

Menelaah Data

In [17]:
# mengungkap tipe-tipe data dari setiap kolom
print(df.dtypes)

Unnamed: 0        int64
id                int64
player_name      object
games             int64
time              int64
goals             int64
xG              float64
assists           int64
xA              float64
shots             int64
key_passes        int64
yellow_cards      int64
red_cards         int64
position         object
team_title       object
npg               int64
npxG            float64
xGChain         float64
xGBuildup       float64
dtype: object

In [18]:
df_noid = df.iloc[:,2:]
df_noid

,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,Harry Kane,35,3097,23,22.174859,14,7.577094,138,49,1,0,F,Tottenham,19,19.130183,24.995648,4.451257
1,Mohamed Salah,37,3085,22,20.250847,5,6.528526,126,55,0,0,F M S,Liverpool,16,15.683834,28.968234,9.800236
2,Bruno Fernandes,37,3117,18,16.019454,12,11.474996,121,95,6,0,M S,Manchester United,9,8.407840,26.911412,11.932285
3,Son Heung-Min,37,3139,17,11.023287,10,9.512992,68,75,0,0,F M S,Tottenham,16,10.262118,20.671916,6.608751
4,Patrick Bamford,38,3085,17,18.401863,7,3.782247,107,30,3,0,F S,Leeds,15,16.879525,23.394953,4.131796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517,Jaden Philogene-Bidace,1,1,0,0.000000,0,0.000000,0,0,0,0,S,Aston Villa,0,0.000000,0.056044,0.056044
518,Gaetano Berardi,2,113,0,0.074761,0,0.000000,1,0,0,0,D S,Leeds,0,0.074761,0.231278,0.231278
519,Anthony Elanga,1,67,0,0.000000,0,0.000000,0,0,0,0,M,Manchester United,0,0.000000,0.000000,0.000000
520,Femi Seriki,1,1,0,0.000000,0,0.000000,0,0,0,0,S,Sheffield United,0,0.000000,0.000000,0.000000
521,Tyrese Francois,1,13,0,0.000000,0,0.000000,0,0,0,0,S,Fulham,0,0.000000,0.000000,0.000000

In [19]:
# menampilkan statistik dasar setiap kolom data yang bertipe numerik.
df_noid.describe()

,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,npg,npxG,xGChain,xGBuildup
count,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000
mean,19.643678,1420.068966,1.862069,2.000806,1.289272,1.376029,17.379310,12.963602,2.061303,0.091954,1.668582,1.821450,5.663368,3.455060
std,11.619836,1031.604819,3.338851,3.317946,2.083350,1.886510,21.572664,16.164361,2.203661,0.295800,2.909929,2.931176,5.600249,3.376584
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,10.000000,470.250000,0.000000,0.074668,0.000000,0.049245,2.000000,1.000000,0.000000,0.000000,0.000000,0.074668,1.191391,0.720353
50%,21.000000,1342.000000,1.000000,0.737295,0.000000,0.691122,10.000000,7.000000,2.000000,0.000000,0.500000,0.715585,4.252738,2.656397
75%,30.000000,2319.000000,2.000000,2.053378,2.000000,2.050509,23.750000,19.000000,3.000000,0.000000,2.000000,1.945799,8.308002,5.254647
max,38.000000,3420.000000,23.000000,22.174859,14.000000,11.474996,138.000000,95.000000,12.000000,2.000000,19.000000,19.130183,28.968234,18.323006

In [20]:
# jika ingin menampilkan juga statistik kolom-
# yang bertipe non-numerik, mencakup beberapa banyak nilai unik-
# dalam kolom (unique), nilai modus(top), serta frekuensi modus(freq)
df_noid.describe(include="all")

,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
count,522,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522,522,522.000000,522.000000,522.000000,522.000000
unique,522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14,28,NaN,NaN,NaN,NaN
top,Tyrese Francois,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M S,Everton,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,106,28,NaN,NaN,NaN,NaN
mean,NaN,19.643678,1420.068966,1.862069,2.000806,1.289272,1.376029,17.379310,12.963602,2.061303,0.091954,NaN,NaN,1.668582,1.821450,5.663368,3.455060
std,NaN,11.619836,1031.604819,3.338851,3.317946,2.083350,1.886510,21.572664,16.164361,2.203661,0.295800,NaN,NaN,2.909929,2.931176,5.600249,3.376584
min,NaN,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000
25%,NaN,10.000000,470.250000,0.000000,0.074668,0.000000,0.049245,2.000000,1.000000,0.000000,0.000000,NaN,NaN,0.000000,0.074668,1.191391,0.720353
50%,NaN,21.000000,1342.000000,1.000000,0.737295,0.000000,0.691122,10.000000,7.000000,2.000000,0.000000,NaN,NaN,0.500000,0.715585,4.252738,2.656397
75%,NaN,30.000000,2319.000000,2.000000,2.053378,2.000000,2.050509,23.750000,19.000000,3.000000,0.000000,NaN,NaN,2.000000,1.945799,8.308002,5.254647
max,NaN,38.000000,3420.000000,23.000000,22.174859,14.000000,11.474996,138.000000,95.000000,12.000000,2.000000,NaN,NaN,19.000000,19.130183,28.968234,18.323006

In [22]:
df_noid.mean(numeric_only=True)

games             19.643678
time            1420.068966
goals              1.862069
xG                 2.000806
assists            1.289272
xA                 1.376029
shots             17.379310
key_passes        12.963602
yellow_cards       2.061303
red_cards          0.091954
npg                1.668582
npxG               1.821450
xGChain            5.663368
xGBuildup          3.455060
dtype: float64

In [23]:
df_noid.sum()

player_name     Harry KaneMohamed SalahBruno FernandesSon Heun...
games                                                       10254
time                                                       741276
goals                                                         972
xG                                                    1044.420572
assists                                                       673
xA                                                     718.287269
shots                                                        9072
key_passes                                                   6767
yellow_cards                                                 1076
red_cards                                                      48
position        FF M SM SF M SF SF SF SFM SF M SF SF SF SF SF ...
team_title      TottenhamLiverpoolManchester UnitedTottenhamLe...
npg                                                           871
npxG                                                     950.7971
xGChain                                               2956.278233
xGBuildup                                             1803.541131
dtype: object

In [25]:
df_noid.median(numeric_only=True)

games             21.000000
time            1342.000000
goals              1.000000
xG                 0.737295
assists            0.000000
xA                 0.691122
shots             10.000000
key_passes         7.000000
yellow_cards       2.000000
red_cards          0.000000
npg                0.500000
npxG               0.715585
xGChain            4.252738
xGBuildup          2.656397
dtype: float64

In [27]:
df_noid.var(numeric_only=True)

games           1.350206e+02
time            1.064209e+06
goals           1.114793e+01
xG              1.100877e+01
assists         4.340345e+00
xA              3.558919e+00
shots           4.653798e+02
key_passes      2.612866e+02
yellow_cards    4.856120e+00
red_cards       8.749752e-02
npg             8.467687e+00
npxG            8.591795e+00
xGChain         3.136279e+01
xGBuildup       1.140132e+01
dtype: float64

In [29]:
df_noid.std(numeric_only=True)

games             11.619836
time            1031.604819
goals              3.338851
xG                 3.317946
assists            2.083350
xA                 1.886510
shots             21.572664
key_passes        16.164361
yellow_cards       2.203661
red_cards          0.295800
npg                2.909929
npxG               2.931176
xGChain            5.600249
xGBuildup          3.376584
dtype: float64

In [31]:
df_noid.quantile(0.75, numeric_only=True)

games             30.000000
time            2319.000000
goals              2.000000
xG                 2.053378
assists            2.000000
xA                 2.050509
shots             23.750000
key_passes        19.000000
yellow_cards       3.000000
red_cards          0.000000
npg                2.000000
npxG               1.945799
xGChain            8.308002
xGBuildup          5.254647
Name: 0.75, dtype: float64

In [33]:
df_num = df_noid.select_dtypes(include='number')

q1 = df_num.quantile(0.25)
q3 = df_num.quantile(0.75)
iqr = q3 - q1

iqr

games             20.000000
time            1848.750000
goals              2.000000
xG                 1.978711
assists            2.000000
xA                 2.001264
shots             21.750000
key_passes        18.000000
yellow_cards       3.000000
red_cards          0.000000
npg                2.000000
npxG               1.871131
xGChain            7.116612
xGBuildup          4.534294
dtype: float64

In [35]:
import warnings
warnings.filterwarnings('ignore')

# ambil kolom numerik saja
df_num = df_noid.select_dtypes(include='number')

# hitung Q1, Q3, IQR
q1 = df_num.quantile(0.25)
q3 = df_num.quantile(0.75)
iqr = q3 - q1

# filter outlier
outlier_filter = (df_num < (q1 - 1.5 * iqr)) | (df_num > (q3 + 1.5 * iqr))

outlier_filter

,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,npg,npxG,xGChain,xGBuildup
0,False,False,True,True,True,True,True,True,False,False,True,True,True,False
1,False,False,True,True,False,True,True,True,False,False,True,True,True,False
2,False,False,True,True,True,True,True,True,False,False,True,True,True,False
3,False,False,True,True,True,True,True,True,False,False,True,True,True,False
4,False,False,True,True,True,False,True,False,False,False,True,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517,False,False,False,False,False,False,False,False,False,False,False,False,False,False
518,False,False,False,False,False,False,False,False,False,False,False,False,False,False
519,False,False,False,False,False,False,False,False,False,False,False,False,False,False
520,False,False,False,False,False,False,False,False,False,False,False,False,False,False
521,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [36]:
df_noid[outlier_filter['assists']] \
    .loc[:, ['player_name', 'assists']] \
    .sort_values(by=['assists'], ascending=False)

                player_name  assists
0                Harry Kane       14
2           Bruno Fernandes       12
58          Kevin De Bruyne       11
51            Jack Grealish       10
3             Son Heung-Min       10
6               Jamie Vardy        9
15          Marcus Rashford        9
57                 Raphinha        9
41            Jack Harrison        8
83              Pascal Groß        8
49              Timo Werner        8
281         Aaron Cresswell        8
130  Trent Alexander-Arnold        7
358             Lucas Digne        7
32        James Ward-Prowse        7
16               Sadio Mané        7
4           Patrick Bamford        7
26          Roberto Firmino        7
204        Andrew Robertson        7
18          Matheus Pereira        6
22          Raheem Sterling        6
42          Bertrand Traoré        6
62               Pedro Neto        6
79             Eberechi Eze        6
137          Bernardo Silva        6
211           Said Benrahma        6
495         Vladimir Coufal        6

In [37]:
df_noid['team_title'].value_counts()

team_title
Everton                          28
West Bromwich Albion             28
Leicester                        27
Liverpool                        27
Southampton                      27
Sheffield United                 27
Wolverhampton Wanderers          27
Manchester United                27
Fulham                           27
Arsenal                          26
Newcastle United                 26
Brighton                         26
Burnley                          25
Chelsea                          25
Tottenham                        24
Manchester City                  24
Crystal Palace                   24
Leeds                            23
Aston Villa                      23
West Ham                         23
Arsenal,Newcastle United          1
Everton,Southampton               1
Aston Villa,Chelsea               1
Liverpool,Southampton             1
Chelsea,Fulham                    1
West Bromwich Albion,West Ham     1
Arsenal,West Bromwich Albion      1
Arsenal,Brighton                  1
Name: count, dtype: int64

Analisis dengan groupby

In [38]:
df.groupby('team_title')['goals'].std()

team_title
Arsenal                          3.352381
Arsenal,Brighton                      NaN
Arsenal,Newcastle United              NaN
Arsenal,West Bromwich Albion          NaN
Aston Villa                      3.696489
Aston Villa,Chelsea                   NaN
Brighton                         2.158703
Burnley                          2.475210
Chelsea                          2.350177
Chelsea,Fulham                        NaN
Crystal Palace                   2.901461
Everton                          3.467727
Everton,Southampton                   NaN
Fulham                           1.439175
Leeds                            4.153193
Leicester                        4.020602
Liverpool                        4.931439
Liverpool,Southampton                 NaN
Manchester City                  3.867132
Manchester United                4.317855
Newcastle United                 2.483174
Sheffield United                 1.467599
Southampton                      3.141941
Tottenham                        5.855135
West Bromwich Albion             2.310260
West Bromwich Albion,West Ham         NaN
West Ham                         3.369240
Wolverhampton Wanderers          1.648620
Name: goals, dtype: float64

In [39]:
df.groupby('team_title')['goals'].mean()

team_title
Arsenal                          1.961538
Arsenal,Brighton                 0.000000
Arsenal,Newcastle United         8.000000
Arsenal,West Bromwich Albion     0.000000
Aston Villa                      2.130435
Aston Villa,Chelsea              3.000000
Brighton                         1.500000
Burnley                          1.280000
Chelsea                          2.240000
Chelsea,Fulham                   1.000000
Crystal Palace                   1.625000
Everton                          1.607143
Everton,Southampton              3.000000
Fulham                           0.925926
Leeds                            2.608696
Leicester                        2.370370
Liverpool                        2.370370
Liverpool,Southampton            3.000000
Manchester City                  3.208333
Manchester United                2.518519
Newcastle United                 1.384615
Sheffield United                 0.666667
Southampton                      1.555556
Tottenham                        2.750000
West Bromwich Albion             1.178571
West Bromwich Albion,West Ham    0.000000
West Ham                         2.478261
Wolverhampton Wanderers          1.222222
Name: goals, dtype: float64

In [41]:
df_noid.select_dtypes(include='number').corr()

,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,npg,npxG,xGChain,xGBuildup
games,1.000000,0.944591,0.439730,0.463869,0.504168,0.562806,0.599164,0.617867,0.565963,0.160326,0.437110,0.465546,0.726598,0.697196
time,0.944591,1.000000,0.398930,0.411203,0.473555,0.516638,0.529534,0.575065,0.592223,0.186333,0.392631,0.408231,0.703801,0.731377
goals,0.439730,0.398930,1.000000,0.932798,0.617490,0.607330,0.873363,0.567752,0.097151,0.053679,0.971591,0.905710,0.727953,0.290990
xG,0.463869,0.411203,0.932798,1.000000,0.636205,0.627495,0.910214,0.570488,0.093761,0.048815,0.894286,0.979218,0.763909,0.282746
assists,0.504168,0.473555,0.617490,0.636205,1.000000,0.885850,0.721220,0.835299,0.209349,-0.021444,0.587316,0.615503,0.752587,0.473254
xA,0.562806,0.516638,0.607330,0.627495,0.885850,1.000000,0.759568,0.946506,0.243912,0.006284,0.585152,0.611100,0.814487,0.547983
shots,0.599164,0.529534,0.873363,0.910214,0.721220,0.759568,1.000000,0.743370,0.249957,0.073932,0.852989,0.901386,0.843152,0.448197
key_passes,0.617867,0.575065,0.567752,0.570488,0.835299,0.946506,0.743370,1.000000,0.343357,0.022780,0.539726,0.545537,0.807958,0.618754
yellow_cards,0.565963,0.592223,0.097151,0.093761,0.209349,0.243912,0.249957,0.343357,1.000000,0.165064,0.093270,0.089065,0.401884,0.562467
red_cards,0.160326,0.186333,0.053679,0.048815,-0.021444,0.006284,0.073932,0.022780,0.165064,1.000000,0.055542,0.047354,0.104005,0.167660
npg,0.437110,0.392631,0.971591,0.894286,0.587316,0.585152,0.852989,0.539726,0.093270,0.055542,1.000000,0.913496,0.720978,0.284135
npxG,0.465546,0.408231,0.905710,0.979218,0.615503,0.611100,0.901386,0.545537,0.089065,0.047354,0.913496,1.000000,0.763481,0.273090
xGChain,0.726598,0.703801,0.727953,0.763909,0.752587,0.814487,0.843152,0.807958,0.401884,0.104005,0.720978,0.763481,1.000000,0.802073
xGBuildup,0.697196,0.731377,0.290990,0.282746,0.473254,0.547983,0.448197,0.618754,0.562467,0.167660,0.284135,0.273090,0.802073,1.000000