<a href="https://colab.research.google.com/github/Nisfah0706/A11.2025.15915_PMesin/blob/main/OneHotEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import library
import random
import pandas as pd
import numpy as np

In [3]:
from google.colab import files
files.upload()

Saving crx.data to crx.data

{'crx.data': b'b,30.83,0,u,g,w,v,1.25,t,t,01,f,g,00202,0,+\na,58.67,4.46,u,g,q,h,3.04,t,t,06,f,g,00043,560,+\na,24.50,0.5,u,g,q,h,1.5,t,f,0,f,g,00280,824,+\nb,27.83,1.54,u,g,w,v,3.75,t,t,05,t,g,00100,3,+\nb,20.17,5.625,u,g,w,v,1.71,t,f,0,f,s,00120,0,+\nb,32.08,4,u,g,m,v,2.5,t,f,0,t,g,00360,0,+\nb,33.17,1.04,u,g,r,h,6.5,t,f,0,t,g,00164,31285,+\na,22.92,11.585,u,g,cc,v,0.04,t,f,0,f,g,00080,1349,+\nb,54.42,0.5,y,p,k,h,3.96,t,f,0,f,g,00180,314,+\nb,42.50,4.915,y,p,w,v,3.165,t,f,0,t,g,00052,1442,+\nb,22.08,0.83,u,g,c,h,2.165,f,f,0,t,g,00128,0,+\nb,29.92,1.835,u,g,c,h,4.335,t,f,0,f,g,00260,200,+\na,38.25,6,u,g,k,v,1,t,f,0,t,g,00000,0,+\nb,48.08,6.04,u,g,k,v,0.04,f,f,0,f,g,00000,2690,+\na,45.83,10.5,u,g,q,v,5,t,t,07,t,g,00000,0,+\nb,36.67,4.415,y,p,k,v,0.25,t,t,10,t,g,00320,0,+\nb,28.25,0.875,u,g,m,v,0.96,t,t,03,t,g,00396,0,+\na,23.25,5.875,u,g,q,v,3.17,t,t,10,f,g,00120,245,+\nb,21.83,0.25,u,g,d,h,0.665,t,f,0,t,g,00000,0,+\na,19.17,8.585,u,g,cc,h,0.75,t,t,07,f,g,00096,0,+\nb,25.00,11.25,u,g,c,v,2.5,t,t,17,f,g,00200,1208,+\nb,23.25,1,u,g,c,v,0.835,t,f,0,f,s,00300,0,+\na,47.75,8,u,g,c,v,7.875,t,t,06,t,g,00000,1260,+\na,27.42,14.5,u,g,x,h,3.085,t,t,01,f,g,00120,11,+\na,41.17,6.5,u,g,q,v,0.5,t,t,03,t,g,00145,0,+\na,15.83,0.585,u,g,c,h,1.5,t,t,02,f,g,00100,0,+\na,47.00,13,u,g,i,bb,5.165,t,t,09,t,g,00000,0,+\nb,56.58,18.5,u,g,d,bb,15,t,t,17,t,g,00000,0,+\nb,57.42,8.5,u,g,e,h,7,t,t,03,f,g,00000,0,+\nb,42.08,1.04,u,g,w,v,5,t,t,06,t,g,00500,10000,+\nb,29.25,14.79,u,g,aa,v,5.04,t,t,05,t,g,00168,0,+\nb,42.00,9.79,u,g,x,h,7.96,t,t,08,f,g,00000,0,+\nb,49.50,7.585,u,g,i,bb,7.585,t,t,15,t,g,00000,5000,+\na,36.75,5.125,u,g,e,v,5,t,f,0,t,g,00000,4000,+\na,22.58,10.75,u,g,q,v,0.415,t,t,05,t,g,00000,560,+\nb,27.83,1.5,u,g,w,v,2,t,t,11,t,g,00434,35,+\nb,27.25,1.585,u,g,cc,h,1.835,t,t,12,t,g,00583,713,+\na,23.00,11.75,u,g,x,h,0.5,t,t,02,t,g,00300,551,+\nb,27.75,0.585,y,p,cc,v,0.25,t,t,02,f,g,00260,500,+\nb,54.58,9.415,u,g,ff,ff,14.415,t,t,11,t,g,00030,300,+\nb,34.17,9.17,u,g,c,v,4.5,t,t,12,t,g,00000,221,+\nb,28.92,15,u,g,c,h,5.335,t,t,11,f,g,00000,2283,+\nb,29.67,1.415,u,g,w,h,0.75,t,t,01,f,g,00240,100,+\nb,39.58,13.915,u,g,w,v,8.625,t,t,06,t,g,00070,0,+\nb,56.42,28,y,p,c,v,28.5,t,t,40,f,g,00000,15,+\nb,54.33,6.75,u,g,c,h,2.625,t,t,11,t,g,00000,284,+\na,41.00,2.04,y,p,q,h,0.125,t,t,23,t,g,00455,1236,+\nb,31.92,4.46,u,g,cc,h,6.04,t,t,03,f,g,00311,300,+\nb,41.50,1.54,u,g,i,bb,3.5,f,f,0,f,g,00216,0,+\nb,23.92,0.665,u,g,c,v,0.165,f,f,0,f,g,00100,0,+\na,25.75,0.5,u,g,c,h,0.875,t,f,0,t,g,00491,0,+\nb,26.00,1,u,g,q,v,1.75,t,f,0,t,g,00280,0,+\nb,37.42,2.04,u,g,w,v,0.04,t,f,0,t,g,00400,5800,+\nb,34.92,2.5,u,g,w,v,0,t,f,0,t,g,00239,200,+\nb,34.25,3,u,g,cc,h,7.415,t,f,0,t,g,00000,0,+\nb,23.33,11.625,y,p,w,v,0.835,t,f,0,t,g,00160,300,+\nb,23.17,0,u,g,cc,v,0.085,t,f,0,f,g,00000,0,+\nb,44.33,0.5,u,g,i,h,5,t,f,0,t,g,00320,0,+\nb,35.17,4.5,u,g,x,h,5.75,f,f,0,t,s,00711,0,+\nb,43.25,3,u,g,q,h,6,t,t,11,f,g,00080,0,+\nb,56.75,12.25,u,g,m,v,1.25,t,t,04,t,g,00200,0,+\nb,31.67,16.165,u,g,d,v,3,t,t,09,f,g,00250,730,+\na,23.42,0.79,y,p,q,v,1.5,t,t,02,t,g,00080,400,+\na,20.42,0.835,u,g,q,v,1.585,t,t,01,f,g,00000,0,+\nb,26.67,4.25,u,g,cc,v,4.29,t,t,01,t,g,00120,0,+\nb,34.17,1.54,u,g,cc,v,1.54,t,t,01,t,g,00520,50000,+\na,36.00,1,u,g,c,v,2,t,t,11,f,g,00000,456,+\nb,25.50,0.375,u,g,m,v,0.25,t,t,03,f,g,00260,15108,+\nb,19.42,6.5,u,g,w,h,1.46,t,t,07,f,g,00080,2954,+\nb,35.17,25.125,u,g,x,h,1.625,t,t,01,t,g,00515,500,+\nb,32.33,7.5,u,g,e,bb,1.585,t,f,0,t,s,00420,0,-\nb,34.83,4,u,g,d,bb,12.5,t,f,0,t,g,?,0,-\na,38.58,5,u,g,cc,v,13.5,t,f,0,t,g,00980,0,-\nb,44.25,0.5,u,g,m,v,10.75,t,f,0,f,s,00400,0,-\nb,44.83,7,y,p,c,v,1.625,f,f,0,f,g,00160,2,-\nb,20.67,5.29,u,g,q,v,0.375,t,t,01,f,g,00160,0,-\nb,34.08,6.5,u,g,aa,v,0.125,t,f,0,t,g,00443,0,-\na,19.17,0.585,y,p,aa,v,0.585,t,f,0,t,g,00160,0,-\nb,21.67,1.165,y,p,k,v,2.5,t,t,01,f,g,00180,20,-\nb,21.50,9.75,u,g,c,v,0.25,t,f,0,f,g,00140,0,-\nb,49.58,19,u,g,ff,ff,0,t,t,01,f,g,00094,0,-\na,27.67,1.5,u,g,m,v,2,t,f,0,f,s,00368,0,-\nb,39.83,0.5,u,g,m,v,0.25,t,f,0,f,s,00288,0,-\na,?,3.5,u,g,d,v,3,t,f,0,t,g,00300,0,-\nb,27.25,0.625,u,g,aa,v,0.455,t,f,0,t,g,00200,0,-\nb,37.17,4,u,g,c,bb,5,t,f,0,t,s,00280,0,-\nb,?,0.375,u,g,d,v,0.875,t,f,0,t,s,00928,0,-\nb,25.67,2.21,y,p,aa,v,4,t,f,0,f,g,00188,0,-\nb,34.00,4.5,u,g,aa,v,1,t,f,0,t,g,00240,0,-\na,49.00,1.5,u,g,j,j,0,t,f,0,t,g,00100,27,-\nb,62.50,12.75,y,p,c,h,5,t,f,0,f,g,00112,0,-\nb,31.42,15.5,u,g,c,v,0.5,t,f,0,f,g,00120,0,-\nb,?,5,y,p,aa,v,8.5,t,f,0,f,g,00000,0,-\nb,52.33,1.375,y,p,c,h,9.46,t,f,0,t,g,00200,100,-\nb,28.75,1.5,y,p,c,v,1.5,t,f,0,t,g,00000,225,-\na,28.58,3.54,u,g,i,bb,0.5,t,f,0,t,g,00171,0,-\nb,23.00,0.625,y,p,aa,v,0.125,t,f,0,f,g,00180,1,-\nb,?,0.5,u,g,c,bb,0.835,t,f,0,t,s,00320,0,-\na,22.50,11,y,p,q,v,3,t,f,0,t,g,00268,0,-\na,28.50,1,u,g,q,v,1,t,t,02,t,g,00167,500,-\nb,37.50,1.75,y,p,c,bb,0.25,t,f,0,t,g,00164,400,-\nb,35.25,16.5,y,p,c,v,4,t,f,0,f,g,00080,0,-\nb,18.67,5,u,g,q,v,0.375,t,t,02,f,g,00000,38,-\nb,25.00,12,u,g,k,v,2.25,t,t,02,t,g,00120,5,-\nb,27.83,4,y,p,i,h,5.75,t,t,02,t,g,00075,0,-\nb,54.83,15.5,u,g,e,z,0,t,t,20,f,g,00152,130,-\nb,28.75,1.165,u,g,k,v,0.5,t,f,0,f,s,00280,0,-\na,25.00,11,y,p,aa,v,4.5,t,f,0,f,g,00120,0,-\nb,40.92,2.25,y,p,x,h,10,t,f,0,t,g,00176,0,-\na,19.75,0.75,u,g,c,v,0.795,t,t,05,t,g,00140,5,-\nb,29.17,3.5,u,g,w,v,3.5,t,t,03,t,g,00329,0,-\na,24.50,1.04,y,p,ff,ff,0.5,t,t,03,f,g,00180,147,-\nb,24.58,12.5,u,g,w,v,0.875,t,f,0,t,g,00260,0,-\na,33.75,0.75,u,g,k,bb,1,t,t,03,t,g,00212,0,-\nb,20.67,1.25,y,p,c,h,1.375,t,t,03,t,g,00140,210,-\na,25.42,1.125,u,g,q,v,1.29,t,t,02,f,g,00200,0,-\nb,37.75,7,u,g,q,h,11.5,t,t,07,t,g,00300,5,-\nb,52.50,6.5,u,g,k,v,6.29,t,t,15,f,g,00000,11202,+\nb,57.83,7.04,u,g,m,v,14,t,t,06,t,g,00360,1332,+\na,20.75,10.335,u,g,cc,h,0.335,t,t,01,t,g,00080,50,+\nb,39.92,6.21,u,g,q,v,0.04,t,t,01,f,g,00200,300,+\nb,25.67,12.5,u,g,cc,v,1.21,t,t,67,t,g,00140,258,+\na,24.75,12.5,u,g,aa,v,1.5,t,t,12,t,g,00120,567,+\na,44.17,6.665,u,g,q,v,7.375,t,t,03,t,g,00000,0,+\na,23.50,9,u,g,q,v,8.5,t,t,05,t,g,00120,0,+\nb,34.92,5,u,g,x,h,7.5,t,t,06,t,g,00000,1000,+\nb,47.67,2.5,u,g,m,bb,2.5,t,t,12,t,g,00410,2510,+\nb,22.75,11,u,g,q,v,2.5,t,t,07,t,g,00100,809,+\nb,34.42,4.25,u,g,i,bb,3.25,t,t,02,f,g,00274,610,+\na,28.42,3.5,u,g,w,v,0.835,t,f,0,f,s,00280,0,+\nb,67.75,5.5,u,g,e,z,13,t,t,01,t,g,00000,0,+\nb,20.42,1.835,u,g,c,v,2.25,t,t,01,f,g,00100,150,+\na,47.42,8,u,g,e,bb,6.5,t,t,06,f,g,00375,51100,+\nb,36.25,5,u,g,c,bb,2.5,t,t,06,f,g,00000,367,+\nb,32.67,5.5,u,g,q,h,5.5,t,t,12,t,g,00408,1000,+\nb,48.58,6.5,u,g,q,h,6,t,f,0,t,g,00350,0,+\nb,39.92,0.54,y,p,aa,v,0.5,t,t,03,f,g,00200,1000,+\nb,33.58,2.75,u,g,m,v,4.25,t,t,06,f,g,00204,0,+\na,18.83,9.5,u,g,w,v,1.625,t,t,06,t,g,00040,600,+\na,26.92,13.5,u,g,q,h,5,t,t,02,f,g,00000,5000,+\na,31.25,3.75,u,g,cc,h,0.625,t,t,09,t,g,00181,0,+\na,56.50,16,u,g,j,ff,0,t,t,15,f,g,00000,247,+\nb,43.00,0.29,y,p,cc,h,1.75,t,t,08,f,g,00100,375,+\nb,22.33,11,u,g,w,v,2,t,t,01,f,g,00080,278,+\nb,27.25,1.665,u,g,cc,h,5.085,t,t,09,f,g,00399,827,+\nb,32.83,2.5,u,g,cc,h,2.75,t,t,06,f,g,00160,2072,+\nb,23.25,1.5,u,g,q,v,2.375,t,t,03,t,g,00000,582,+\na,40.33,7.54,y,p,q,h,8,t,t,14,f,g,00000,2300,+\na,30.50,6.5,u,g,c,bb,4,t,t,07,t,g,00000,3065,+\na,52.83,15,u,g,c,v,5.5,t,t,14,f,g,00000,2200,+\na,46.67,0.46,u,g,cc,h,0.415,t,t,11,t,g,00440,6,+\na,58.33,10,u,g,q,v,4,t,t,14,f,g,00000,1602,+\nb,37.33,6.5,u,g,m,h,4.25,t,t,12,t,g,00093,0,+\nb,23.08,2.5,u,g,c,v,1.085,t,t,11,t,g,00060,2184,+\nb,32.75,1.5,u,g,cc,h,5.5,t,t,03,t,g,00000,0,+\na,21.67,11.5,y,p,j,j,0,t,t,11,t,g,00000,0,+\na,28.50,3.04,y,p,x,h,2.54,t,t,01,f,g,00070,0,+\na,68.67,15,u,g,e,z,0,t,t,14,f,g,00000,3376,+\nb,28.00,2,u,g,k,h,4.165,t,t,02,t,g,00181,0,+\nb,34.08,0.08,y,p,m,bb,0.04,t,t,01,t,g,00280,2000,+\nb,27.67,2,u,g,x,h,1,t,t,04,f,g,00140,7544,+\nb,44.00,2,u,g,m,v,1.75,t,t,02,t,g,00000,15,+\nb,25.08,1.71,u,g,x,v,1.665,t,t,01,t,g,00395,20,+\nb,32.00,1.75,y,p,e,h,0.04,t,f,0,t,g,00393,0,+\na,60.58,16.5,u,g,q,v,11,t,f,0,t,g,00021,10561,+\na,40.83,10,u,g,q,h,1.75,t,f,0,f,g,00029,837,+\nb,19.33,9.5,u,g,q,v,1,t,f,0,t,g,00060,400,+\na,32.33,0.54,u,g,cc,v,0.04,t,f,0,f,g,00440,11177,+\nb,36.67,3.25,u,g,q,h,9,t,f,0,t,g,00102,639,+\nb,37.50,1.125,y,p,d,v,1.5,f,f,0,t,g,00431,0,+\na,25.08,2.54,y,p,aa,v,0.25,t,f,0,t,g,00370,0,+\nb,41.33,0,u,g,c,bb,15,t,f,0,f,g,00000,0,+\nb,56.00,12.5,u,g,k,h,8,t,f,0,t,g,00024,2028,+\na,49.83,13.585,u,g,k,h,8.5,t,f,0,t,g,00000,0,+\nb,22.67,10.5,u,g,q,h,1.335,t,f,0,f,g,00100,0,+\nb,27.00,1.5,y,p,w,v,0.375,t,f,0,t,g,00260,1065,+\nb,25.00,12.5,u,g,aa,v,3,t,f,0,t,s,00020,0,+\na,26.08,8.665,u,g,aa,v,1.415,t,f,0,f,g,00160,150,+\na,18.42,9.25,u,g,q,v,1.21,t,t,04,f,g,00060,540,+\nb,20.17,8.17,u,g,aa,v,1.96,t,t,14,f,g,00060,158,+\nb,47.67,0.29,u,g,c,bb,15,t,t,20,f,g,00000,15000,+\na,21.25,2.335,u,g,i,bb,0.5,t,t,04,f,s,00080,0,+\na,20.67,3,u,g,q,v,0.165,t,t,03,f,g,00100,6,+\na,57.08,19.5,u,g,c,v,5.5,t,t,07,f,g,00000,3000,+\na,22.42,5.665,u,g,q,v,2.585,t,t,07,f,g,00129,3257,+\nb,48.75,8.5,u,g,c,h,12.5,t,t,09,f,g,00181,1655,+\nb,40.00,6.5,u,g,aa,bb,3.5,t,t,01,f,g,00000,500,+\nb,40.58,5,u,g,c,v,5,t,t,07,f,g,00000,3065,+\na,28.67,1.04,u,g,c,v,2.5,t,t,05,t,g,00300,1430,+\na,33.08,4.625,u,g,q,h,1.625,t,t,02,f,g,00000,0,+\nb,21.33,10.5,u,g,c,v,3,t,f,0,t,g,00000,0,+\nb,42.00,0.205,u,g,i,h,5.125,t,f,0,f,g,00400,0,+\nb,41.75,0.96,u,g,x,v,2.5,t,f,0,f,g,00510,600,+\nb,22.67,1.585,y,p,w,v,3.085,t,t,06,f,g,00080,0,+\nb,34.50,4.04,y,p,i,bb,8.5,t,t,07,t,g,00195,0,+\nb,28.25,5.04,y,p,c,bb,1.5,t,t,08,t,g,00144,7,+\nb,33.17,3.165,y,p,x,v,3.165,t,t,03,t,g,00380,0,+\nb,48.17,7.625,u,g,w,h,15.5,t,t,12,f,g,00000,790,+\nb,27.58,2.04,y,p,aa,v,2,t,t,03,t,g,00370,560,+\nb,22.58,10.04,u,g,x,v,0.04,t,t,09,f,g,00060,396,+\na,24.08,0.5,u,g,q,h,1.25,t,t,01,f,g,00000,678,+\na,41.33,1,u,g,i,bb,2.25,t,f,0,t,g,00000,300,+\nb,24.83,2.75,u,g,c,v,2.25,t,t,06,f,g,?,600,+\na,20.75,10.25,u,g,q,v,0.71,t,t,02,t,g,00049,0,+\nb,36.33,2.125,y,p,w,v,0.085,t,t,01,f,g,00050,1187,+\na,35.42,12,u,g,q,h,14,t,t,08,f,g,00000,6590,+\na,71.58,0,?,?,?,?,0,f,f,0,f,p,?,0,+\nb,28.67,9.335,u,g,q,h,5.665,t,t,06,f,g,00381,168,+\nb,35.17,2.5,u,g,k,v,4.5,t,t,07,f,g,00150,1270,+\nb,39.50,4.25,u,g,c,bb,6.5,t,t,16,f,g,00117,1210,+\nb,39.33,5.875,u,g,cc,h,10,t,t,14,t,g,00399,0,+\nb,24.33,6.625,y,p,d,v,5.5,t,f,0,t,s,00100,0,+\nb,60.08,14.5,u,g,ff,ff,18,t,t,15,t,g,00000,1000,+\nb,23.08,11.5,u,g,i,v,3.5,t,t,09,f,g,00056,742,+\nb,26.67,2.71,y,p,cc,v,5.25,t,t,01,f,g,00211,0,+\nb,48.17,3.5,u,g,aa,v,3.5,t,f,0,f,s,00230,0,+\nb,41.17,4.04,u,g,cc,h,7,t,t,08,f,g,00320,0,+\nb,55.92,11.5,u,g,ff,ff,5,t,t,05,f,g,00000,8851,+\nb,53.92,9.625,u,g,e,v,8.665,t,t,05,f,g,00000,0,+\na,18.92,9.25,y,p,c,v,1,t,t,04,t,g,00080,500,+\na,50.08,12.54,u,g,aa,v,2.29,t,t,03,t,g,00156,0,+\nb,65.42,11,u,g,e,z,20,t,t,07,t,g,00022,0,+\na,17.58,9,u,g,aa,v,1.375,t,f,0,t,g,00000,0,+\na,18.83,9.54,u,g,aa,v,0.085,t,f,0,f,g,00100,0,+\na,37.75,5.5,u,g,q,v,0.125,t,f,0,t,g,00228,0,+\nb,23.25,4,u,g,c,bb,0.25,t,f,0,t,g,00160,0,+\nb,18.08,5.5,u,g,k,v,0.5,t,f,0,f,g,00080,0,+\na,22.50,8.46,y,p,x,v,2.46,f,f,0,f,g,00164,0,+\nb,19.67,0.375,u,g,q,v,2,t,t,02,t,g,00080,0,+\nb,22.08,11,u,g,cc,v,0.665,t,f,0,f,g,00100,0,+\nb,25.17,3.5,u,g,cc,v,0.625,t,t,07,f,g,00000,7059,+\na,47.42,3,u,g,x,v,13.875,t,t,02,t,g,00519,1704,+\nb,33.50,1.75,u,g,x,h,4.5,t,t,04,t,g,00253,857,+\nb,27.67,13.75,u,g,w,v,5.75,t,f,0,t,g,00487,500,+\na,58.42,21,u,g,i,bb,10,t,t,13,f,g,00000,6700,+\na,20.67,1.835,u,g,q,v,2.085,t,t,05,f,g,00220,2503,+\nb,26.17,0.25,u,g,i,bb,0,t,f,0,t,g,00000,0,+\nb,21.33,7.5,u,g,aa,v,1.415,t,t,01,f,g,00080,9800,+\nb,42.83,4.625,u,g,q,v,4.58,t,f,0,f,s,00000,0,+\nb,38.17,10.125,u,g,x,v,2.5,t,t,06,f,g,00520,196,+\nb,20.50,10,y,p,c,v,2.5,t,f,0,f,s,00040,0,+\nb,48.25,25.085,u,g,w,v,1.75,t,t,03,f,g,00120,14,+\nb,28.33,5,u,g,w,v,11,t,f,0,t,g,00070,0,+\na,18.75,7.5,u,g,q,v,2.71,t,t,05,f,g,?,26726,+\nb,18.50,2,u,g,i,v,1.5,t,t,02,f,g,00120,300,+\nb,33.17,3.04,y,p,c,h,2.04,t,t,01,t,g,00180,18027,+\nb,45.00,8.5,u,g,cc,h,14,t,t,01,t,g,00088,2000,+\na,19.67,0.21,u,g,q,h,0.29,t,t,11,f,g,00080,99,+\n?,24.50,12.75,u,g,c,bb,4.75,t,t,02,f,g,00073,444,+\nb,21.83,11,u,g,x,v,0.29,t,t,06,f,g,00121,0,+\nb,40.25,21.5,u,g,e,z,20,t,t,11,f,g,00000,1200,+\nb,41.42,5,u,g,q,h,5,t,t,06,t,g,00470,0,+\na,17.83,11,u,g,x,h,1,t,t,11,f,g,00000,3000,+\nb,23.17,11.125,u,g,x,h,0.46,t,t,01,f,g,00100,0,+\nb,?,0.625,u,g,k,v,0.25,f,f,0,f,g,00380,2010,-\nb,18.17,10.25,u,g,c,h,1.085,f,f,0,f,g,00320,13,-\nb,20.00,11.045,u,g,c,v,2,f,f,0,t,g,00136,0,-\nb,20.00,0,u,g,d,v,0.5,f,f,0,f,g,00144,0,-\na,20.75,9.54,u,g,i,v,0.04,f,f,0,f,g,00200,1000,-\na,24.50,1.75,y,p,c,v,0.165,f,f,0,f,g,00132,0,-\nb,32.75,2.335,u,g,d,h,5.75,f,f,0,t,g,00292,0,-\na,52.17,0,y,p,ff,ff,0,f,f,0,f,g,00000,0,-\na,48.17,1.335,u,g,i,o,0.335,f,f,0,f,g,00000,120,-\na,20.42,10.5,y,p,x,h,0,f,f,0,t,g,00154,32,-\nb,50.75,0.585,u,g,ff,ff,0,f,f,0,f,g,00145,0,-\nb,17.08,0.085,y,p,c,v,0.04,f,f,0,f,g,00140,722,-\nb,18.33,1.21,y,p,e,dd,0,f,f,0,f,g,00100,0,-\na,32.00,6,u,g,d,v,1.25,f,f,0,f,g,00272,0,-\nb,59.67,1.54,u,g,q,v,0.125,t,f,0,t,g,00260,0,+\nb,18.00,0.165,u,g,q,n,0.21,f,f,0,f,g,00200,40,+\nb,37.58,0,?,?,?,?,0,f,f,0,f,p,?,0,+\nb,32.33,2.5,u,g,c,v,1.25,f,f,0,t,g,00280,0,-\nb,18.08,6.75,y,p,m,v,0.04,f,f,0,f,g,00140,0,-\nb,38.25,10.125,y,p,k,v,0.125,f,f,0,f,g,00160,0,-\nb,30.67,2.5,u,g,cc,h,2.25,f,f,0,t,s,00340,0,-\nb,18.58,5.71,u,g,d,v,0.54,f,f,0,f,g,00120,0,-\na,19.17,5.415,u,g,i,h,0.29,f,f,0,f,g,00080,484,-\na,18.17,10,y,p,q,h,0.165,f,f,0,f,g,00340,0,-\nb,24.58,13.5,y,p,ff,ff,0,f,f,0,f,g,?,0,-\nb,16.25,0.835,u,g,m,v,0.085,t,f,0,f,s,00200,0,-\nb,21.17,0.875,y,p,c,h,0.25,f,f,0,f,g,00280,204,-\nb,23.92,0.585,y,p,cc,h,0.125,f,f,0,f,g,00240,1,-\nb,17.67,4.46,u,g,c,v,0.25,f,f,0,f,s,00080,0,-\na,16.50,1.25,u,g,q,v,0.25,f,t,01,f,g,00108,98,-\nb,23.25,12.625,u,g,c,v,0.125,f,t,02,f,g,00000,5552,-\nb,17.58,10,u,g,w,h,0.165,f,t,01,f,g,00120,1,-\na,?,1.5,u,g,ff,ff,0,f,t,02,t,g,00200,105,-\nb,29.50,0.58,u,g,w,v,0.29,f,t,01,f,g,00340,2803,-\nb,18.83,0.415,y,p,c,v,0.165,f,t,01,f,g,00200,1,-\na,21.75,1.75,y,p,j,j,0,f,f,0,f,g,00160,0,-\nb,23.00,0.75,u,g,m,v,0.5,f,f,0,t,s,00320,0,-\na,18.25,10,u,g,w,v,1,f,t,01,f,g,00120,1,-\nb,25.42,0.54,u,g,w,v,0.165,f,t,01,f,g,00272,444,-\nb,35.75,2.415,u,g,w,v,0.125,f,t,02,f,g,00220,1,-\na,16.08,0.335,u,g,ff,ff,0,f,t,01,f,g,00160,126,-\na,31.92,3.125,u,g,ff,ff,3.04,f,t,02,t,g,00200,4,-\nb,69.17,9,u,g,ff,ff,4,f,t,01,f,g,00070,6,-\nb,32.92,2.5,u,g,aa,v,1.75,f,t,02,t,g,00720,0,-\nb,16.33,2.75,u,g,aa,v,0.665,f,t,01,f,g,00080,21,-\nb,22.17,12.125,u,g,c,v,3.335,f,t,02,t,g,00180,173,-\na,57.58,2,u,g,ff,ff,6.5,f,t,01,f,g,00000,10,-\nb,18.25,0.165,u,g,d,v,0.25,f,f,0,t,s,00280,0,-\nb,23.42,1,u,g,c,v,0.5,f,f,0,t,s,00280,0,-\na,15.92,2.875,u,g,q,v,0.085,f,f,0,f,g,00120,0,-\na,24.75,13.665,u,g,q,h,1.5,f,f,0,f,g,00280,1,-\nb,48.75,26.335,y,p,ff,ff,0,t,f,0,t,g,00000,0,-\nb,23.50,2.75,u,g,ff,ff,4.5,f,f,0,f,g,00160,25,-\nb,18.58,10.29,u,g,ff,ff,0.415,f,f,0,f,g,00080,0,-\nb,27.75,1.29,u,g,k,h,0.25,f,f,0,t,s,00140,0,-\na,31.75,3,y,p,j,j,0,f,f,0,f,g,00160,20,-\na,24.83,4.5,u,g,w,v,1,f,f,0,t,g,00360,6,-\nb,19.00,1.75,y,p,c,v,2.335,f,f,0,t,g,00112,6,-\na,16.33,0.21,u,g,aa,v,0.125,f,f,0,f,g,00200,1,-\na,18.58,10,u,g,d,v,0.415,f,f,0,f,g,00080,42,-\nb,16.25,0,y,p,aa,v,0.25,f,f,0,f,g,00060,0,-\nb,23.00,0.75,u,g,m,v,0.5,t,f,0,t,s,00320,0,-\nb,21.17,0.25,y,p,c,h,0.25,f,f,0,f,g,00280,204,-\nb,17.50,22,l,gg,ff,o,0,f,f,0,t,p,00450,100000,+\nb,19.17,0,y,p,m,bb,0,f,f,0,t,s,00500,1,+\nb,36.75,0.125,y,p,c,v,1.5,f,f,0,t,g,00232,113,+\nb,21.25,1.5,u,g,w,v,1.5,f,f,0,f,g,00150,8,+\na,18.08,0.375,l,gg,cc,ff,10,f,f,0,t,s,00300,0,+\na,33.67,0.375,u,g,cc,v,0.375,f,f,0,f,g,00300,44,+\nb,48.58,0.205,y,p,k,v,0.25,t,t,11,f,g,00380,2732,+\nb,33.67,1.25,u,g,w,v,1.165,f,f,0,f,g,00120,0,-\na,29.50,1.085,y,p,x,v,1,f,f,0,f,g,00280,13,-\nb,30.17,1.085,y,p,c,v,0.04,f,f,0,f,g,00170,179,-\n?,40.83,3.5,u,g,i,bb,0.5,f,f,0,f,s,01160,0,-\nb,34.83,2.5,y,p,w,v,3,f,f,0,f,s,00200,0,-\nb,?,4,y,p,i,v,0.085,f,f,0,t,g,00411,0,-\nb,20.42,0,?,?,?,?,0,f,f,0,f,p,?,0,-\na,33.25,2.5,y,p,c,v,2.5,f,f,0,t,g,00000,2,-\nb,34.08,2.5,u,g,c,v,1,f,f,0,f,g,00460,16,-\na,25.25,12.5,u,g,d,v,1,f,f,0,t,g,00180,1062,-\nb,34.75,2.5,u,g,cc,bb,0.5,f,f,0,f,g,00348,0,-\nb,27.67,0.75,u,g,q,h,0.165,f,f,0,t,g,00220,251,-\nb,47.33,6.5,u,g,c,v,1,f,f,0,t,g,00000,228,-\na,34.83,1.25,y,p,i,h,0.5,f,f,0,t,g,00160,0,-\na,33.25,3,y,p,aa,v,2,f,f,0,f,g,00180,0,-\nb,28.00,3,u,g,w,v,0.75,f,f,0,t,g,00300,67,-\na,39.08,4,u,g,c,v,3,f,f,0,f,g,00480,0,-\nb,42.75,4.085,u,g,aa,v,0.04,f,f,0,f,g,00108,100,-\nb,26.92,2.25,u,g,i,bb,0.5,f,f,0,t,g,00640,4000,-\nb,33.75,2.75,u,g,i,bb,0,f,f,0,f,g,00180,0,-\nb,38.92,1.75,u,g,k,v,0.5,f,f,0,t,g,00300,2,-\nb,62.75,7,u,g,e,z,0,f,f,0,f,g,00000,12,-\n?,32.25,1.5,u,g,c,v,0.25,f,f,0,t,g,00372,122,-\nb,26.75,4.5,y,p,c,bb,2.5,f,f,0,f,g,00200,1210,-\nb,63.33,0.54,u,g,c,v,0.585,t,t,03,t,g,00180,0,-\nb,27.83,1.5,u,g,w,v,2.25,f,t,01,t,g,00100,3,-\na,26.17,2,u,g,j,j,0,f,f,0,t,g,00276,1,-\nb,22.17,0.585,y,p,ff,ff,0,f,f,0,f,g,00100,0,-\nb,22.50,11.5,y,p,m,v,1.5,f,f,0,t,g,00000,4000,-\nb,30.75,1.585,u,g,d,v,0.585,f,f,0,t,s,00000,0,-\nb,36.67,2,u,g,i,v,0.25,f,f,0,t,g,00221,0,-\na,16.00,0.165,u,g,aa,v,1,f,t,02,t,g,00320,1,-\nb,41.17,1.335,u,g,d,v,0.165,f,f,0,f,g,00168,0,-\na,19.50,0.165,u,g,q,v,0.04,f,f,0,t,g,00380,0,-\nb,32.42,3,u,g,d,v,0.165,f,f,0,t,g,00120,0,-\na,36.75,4.71,u,g,ff,ff,0,f,f,0,f,g,00160,0,-\na,30.25,5.5,u,g,k,v,5.5,f,f,0,t,s,00100,0,-\nb,23.08,2.5,u,g,ff,ff,0.085,f,f,0,t,g,00100,4208,-\nb,26.83,0.54,u,g,k,ff,0,f,f,0,f,g,00100,0,-\nb,16.92,0.335,y,p,k,v,0.29,f,f,0,f,s,00200,0,-\nb,24.42,2,u,g,e,dd,0.165,f,t,02,f,g,00320,1300,-\nb,42.83,1.25,u,g,m,v,13.875,f,t,01,t,g,00352,112,-\na,22.75,6.165,u,g,aa,v,0.165,f,f,0,f,g,00220,1000,-\nb,39.42,1.71,y,p,m,v,0.165,f,f,0,f,s,00400,0,-\na,23.58,11.5,y,p,k,h,3,f,f,0,t,g,00020,16,-\nb,21.42,0.75,y,p,r,n,0.75,f,f,0,t,g,00132,2,-\nb,33.00,2.5,y,p,w,v,7,f,f,0,t,g,00280,0,-\nb,26.33,13,u,g,e,dd,0,f,f,0,t,g,00140,1110,-\na,45.00,4.585,u,g,k,h,1,f,f,0,t,s,00240,0,-\nb,26.25,1.54,u,g,w,v,0.125,f,f,0,f,g,00100,0,-\n?,28.17,0.585,u,g,aa,v,0.04,f,f,0,f,g,00260,1004,-\na,20.83,0.5,y,p,e,dd,1,f,f,0,f,g,00260,0,-\nb,28.67,14.5,u,g,d,v,0.125,f,f,0,f,g,00000,286,-\nb,20.67,0.835,y,p,c,v,2,f,f,0,t,s,00240,0,-\nb,34.42,1.335,u,g,i,bb,0.125,f,f,0,t,g,00440,4500,-\nb,33.58,0.25,u,g,i,bb,4,f,f,0,t,s,00420,0,-\nb,43.17,5,u,g,i,bb,2.25,f,f,0,t,g,00141,0,-\na,22.67,7,u,g,c,v,0.165,f,f,0,f,g,00160,0,-\na,24.33,2.5,y,p,i,bb,4.5,f,f,0,f,g,00200,456,-\na,56.83,4.25,y,p,ff,ff,5,f,f,0,t,g,00000,4,-\nb,22.08,11.46,u,g,k,v,1.585,f,f,0,t,g,00100,1212,-\nb,34.00,5.5,y,p,c,v,1.5,f,f,0,t,g,00060,0,-\nb,22.58,1.5,y,p,aa,v,0.54,f,f,0,t,g,00120,67,-\nb,21.17,0,u,g,c,v,0.5,f,f,0,t,s,00000,0,-\nb,26.67,14.585,u,g,i,bb,0,f,f,0,t,g,00178,0,-\nb,22.92,0.17,u,g,m,v,0.085,f,f,0,f,s,00000,0,-\nb,15.17,7,u,g,e,v,1,f,f,0,f,g,00600,0,-\nb,39.92,5,u,g,i,bb,0.21,f,f,0,f,g,00550,0,-\nb,27.42,12.5,u,g,aa,bb,0.25,f,f,0,t,g,00720,0,-\nb,24.75,0.54,u,g,m,v,1,f,f,0,t,g,00120,1,-\nb,41.17,1.25,y,p,w,v,0.25,f,f,0,f,g,00000,195,-\na,33.08,1.625,u,g,d,v,0.54,f,f,0,t,g,00000,0,-\nb,29.83,2.04,y,p,x,h,0.04,f,f,0,f,g,00128,1,-\na,23.58,0.585,y,p,ff,ff,0.125,f,f,0,f,g,00120,87,-\nb,26.17,12.5,y,p,k,h,1.25,f,f,0,t,g,00000,17,-\nb,31.00,2.085,u,g,c,v,0.085,f,f,0,f,g,00300,0,-\nb,20.75,5.085,y,p,j,v,0.29,f,f,0,f,g,00140,184,-\nb,28.92,0.375,u,g,c,v,0.29,f,f,0,f,g,00220,140,-\na,51.92,6.5,u,g,i,bb,3.085,f,f,0,t,g,00073,0,-\na,22.67,0.335,u,g,q,v,0.75,f,f,0,f,s,00160,0,-\nb,34.00,5.085,y,p,i,bb,1.085,f,f,0,t,g,00480,0,-\na,69.50,6,u,g,ff,ff,0,f,f,0,f,s,00000,0,-\na,40.33,8.125,y,p,k,v,0.165,f,t,02,f,g,?,18,-\na,19.58,0.665,y,p,c,v,1,f,t,01,f,g,02000,2,-\nb,16.00,3.125,u,g,w,v,0.085,f,t,01,f,g,00000,6,-\nb,17.08,0.25,u,g,q,v,0.335,f,t,04,f,g,00160,8,-\nb,31.25,2.835,u,g,ff,ff,0,f,t,05,f,g,00176,146,-\nb,25.17,3,u,g,c,v,1.25,f,t,01,f,g,00000,22,-\na,22.67,0.79,u,g,i,v,0.085,f,f,0,f,g,00144,0,-\nb,40.58,1.5,u,g,i,bb,0,f,f,0,f,s,00300,0,-\nb,22.25,0.46,u,g,k,v,0.125,f,f,0,t,g,00280,55,-\na,22.25,1.25,y,p,ff,ff,3.25,f,f,0,f,g,00280,0,-\nb,22.50,0.125,y,p,k,v,0.125,f,f,0,f,g,00200,70,-\nb,23.58,1.79,u,g,c,v,0.54,f,f,0,t,g,00136,1,-\nb,38.42,0.705,u,g,c,v,0.375,f,t,02,f,g,00225,500,-\na

In [4]:
# Membaca data mentah (raw data)
data = pd.read_csv('crx.data', header=None)

In [5]:
# Membentuk list Fitur A1..A17

varnames = ['A'+str(s) for s in range(1,17)]

# Men-set masing-masing kolom dari data yang ada
# Hal ini dilakukan karena data mentah yang dipakai tidak memiliki judul fitur
data.columns = varnames

# Mengganti data dengan nilai ? dengan nilai Nan
data = data.replace('?', np.nan)

In [6]:
# merubah tipe data dari kolom A2 dan A14 menjadi tipe float
data['A2'] = data['A2'].astype('float')
data['A14'] = data['A14'].astype('float')

In [7]:
#melakukan proses maping data text menjadi menjadi bentuk binary
data['A16'] = data['A16'].map({'+':1, '-':0})

In [8]:
#membuat list dengan fitur data dengan jenis kategori dan jenis numerik
cat_cols = [c for c in data.columns if data[c].dtypes=='O']
num_cols = [c for c in data.columns if data[c].dtypes!='O']

In [9]:
# melakukan inputasi terhadap data yang kosong dengan nilai
# 0 untuk list data bernilai numerik
# Missing untuk data kolom fitur berjenis kategori
data[num_cols] = data[num_cols].fillna(0)
data[cat_cols] = data[cat_cols].fillna('Missing')

#menyimpan data yang telah di transformasi dalam bentuk csv
data.to_csv('creditApprovalUCI.csv', index=False)

Pelabelan Data

In [10]:
### Pada sesi lab ini dibutuhkan library sklearn, silahkan anda melakukan instalasi dengan perintah berikut :
### pip install sklearn
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [11]:
from google.colab import files
files.upload()

Saving creditApprovalUCI.csv to creditApprovalUCI (1).csv

{'creditApprovalUCI (1).csv': b'A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14,A15,A16\nb,30.83,0.0,u,g,w,v,1.25,t,t,1,f,g,202.0,0,1\na,58.67,4.46,u,g,q,h,3.04,t,t,6,f,g,43.0,560,1\na,24.5,0.5,u,g,q,h,1.5,t,f,0,f,g,280.0,824,1\nb,27.83,1.54,u,g,w,v,3.75,t,t,5,t,g,100.0,3,1\nb,20.17,5.625,u,g,w,v,1.71,t,f,0,f,s,120.0,0,1\nb,32.08,4.0,u,g,m,v,2.5,t,f,0,t,g,360.0,0,1\nb,33.17,1.04,u,g,r,h,6.5,t,f,0,t,g,164.0,31285,1\na,22.92,11.585,u,g,cc,v,0.04,t,f,0,f,g,80.0,1349,1\nb,54.42,0.5,y,p,k,h,3.96,t,f,0,f,g,180.0,314,1\nb,42.5,4.915,y,p,w,v,3.165,t,f,0,t,g,52.0,1442,1\nb,22.08,0.83,u,g,c,h,2.165,f,f,0,t,g,128.0,0,1\nb,29.92,1.835,u,g,c,h,4.335,t,f,0,f,g,260.0,200,1\na,38.25,6.0,u,g,k,v,1.0,t,f,0,t,g,0.0,0,1\nb,48.08,6.04,u,g,k,v,0.04,f,f,0,f,g,0.0,2690,1\na,45.83,10.5,u,g,q,v,5.0,t,t,7,t,g,0.0,0,1\nb,36.67,4.415,y,p,k,v,0.25,t,t,10,t,g,320.0,0,1\nb,28.25,0.875,u,g,m,v,0.96,t,t,3,t,g,396.0,0,1\na,23.25,5.875,u,g,q,v,3.17,t,t,10,f,g,120.0,245,1\nb,21.83,0.25,u,g,d,h,0.665,t,f,0,t,g,0.0,0,1\na,19.17,8.585,u,g,cc,h,0.75,t,t,7,f,g,96.0,0,1\nb,25.0,11.25,u,g,c,v,2.5,t,t,17,f,g,200.0,1208,1\nb,23.25,1.0,u,g,c,v,0.835,t,f,0,f,s,300.0,0,1\na,47.75,8.0,u,g,c,v,7.875,t,t,6,t,g,0.0,1260,1\na,27.42,14.5,u,g,x,h,3.085,t,t,1,f,g,120.0,11,1\na,41.17,6.5,u,g,q,v,0.5,t,t,3,t,g,145.0,0,1\na,15.83,0.585,u,g,c,h,1.5,t,t,2,f,g,100.0,0,1\na,47.0,13.0,u,g,i,bb,5.165,t,t,9,t,g,0.0,0,1\nb,56.58,18.5,u,g,d,bb,15.0,t,t,17,t,g,0.0,0,1\nb,57.42,8.5,u,g,e,h,7.0,t,t,3,f,g,0.0,0,1\nb,42.08,1.04,u,g,w,v,5.0,t,t,6,t,g,500.0,10000,1\nb,29.25,14.79,u,g,aa,v,5.04,t,t,5,t,g,168.0,0,1\nb,42.0,9.79,u,g,x,h,7.96,t,t,8,f,g,0.0,0,1\nb,49.5,7.585,u,g,i,bb,7.585,t,t,15,t,g,0.0,5000,1\na,36.75,5.125,u,g,e,v,5.0,t,f,0,t,g,0.0,4000,1\na,22.58,10.75,u,g,q,v,0.415,t,t,5,t,g,0.0,560,1\nb,27.83,1.5,u,g,w,v,2.0,t,t,11,t,g,434.0,35,1\nb,27.25,1.585,u,g,cc,h,1.835,t,t,12,t,g,583.0,713,1\na,23.0,11.75,u,g,x,h,0.5,t,t,2,t,g,300.0,551,1\nb,27.75,0.585,y,p,cc,v,0.25,t,t,2,f,g,260.0,500,1\nb,54.58,9.415,u,g,ff,ff,14.415,t,t,11,t,g,30.0,300,1\nb,34.17,9.17,u,g,c,v,4.5,t,t,12,t,g,0.0,221,1\nb,28.92,15.0,u,g,c,h,5.335,t,t,11,f,g,0.0,2283,1\nb,29.67,1.415,u,g,w,h,0.75,t,t,1,f,g,240.0,100,1\nb,39.58,13.915,u,g,w,v,8.625,t,t,6,t,g,70.0,0,1\nb,56.42,28.0,y,p,c,v,28.5,t,t,40,f,g,0.0,15,1\nb,54.33,6.75,u,g,c,h,2.625,t,t,11,t,g,0.0,284,1\na,41.0,2.04,y,p,q,h,0.125,t,t,23,t,g,455.0,1236,1\nb,31.92,4.46,u,g,cc,h,6.04,t,t,3,f,g,311.0,300,1\nb,41.5,1.54,u,g,i,bb,3.5,f,f,0,f,g,216.0,0,1\nb,23.92,0.665,u,g,c,v,0.165,f,f,0,f,g,100.0,0,1\na,25.75,0.5,u,g,c,h,0.875,t,f,0,t,g,491.0,0,1\nb,26.0,1.0,u,g,q,v,1.75,t,f,0,t,g,280.0,0,1\nb,37.42,2.04,u,g,w,v,0.04,t,f,0,t,g,400.0,5800,1\nb,34.92,2.5,u,g,w,v,0.0,t,f,0,t,g,239.0,200,1\nb,34.25,3.0,u,g,cc,h,7.415,t,f,0,t,g,0.0,0,1\nb,23.33,11.625,y,p,w,v,0.835,t,f,0,t,g,160.0,300,1\nb,23.17,0.0,u,g,cc,v,0.085,t,f,0,f,g,0.0,0,1\nb,44.33,0.5,u,g,i,h,5.0,t,f,0,t,g,320.0,0,1\nb,35.17,4.5,u,g,x,h,5.75,f,f,0,t,s,711.0,0,1\nb,43.25,3.0,u,g,q,h,6.0,t,t,11,f,g,80.0,0,1\nb,56.75,12.25,u,g,m,v,1.25,t,t,4,t,g,200.0,0,1\nb,31.67,16.165,u,g,d,v,3.0,t,t,9,f,g,250.0,730,1\na,23.42,0.79,y,p,q,v,1.5,t,t,2,t,g,80.0,400,1\na,20.42,0.835,u,g,q,v,1.585,t,t,1,f,g,0.0,0,1\nb,26.67,4.25,u,g,cc,v,4.29,t,t,1,t,g,120.0,0,1\nb,34.17,1.54,u,g,cc,v,1.54,t,t,1,t,g,520.0,50000,1\na,36.0,1.0,u,g,c,v,2.0,t,t,11,f,g,0.0,456,1\nb,25.5,0.375,u,g,m,v,0.25,t,t,3,f,g,260.0,15108,1\nb,19.42,6.5,u,g,w,h,1.46,t,t,7,f,g,80.0,2954,1\nb,35.17,25.125,u,g,x,h,1.625,t,t,1,t,g,515.0,500,1\nb,32.33,7.5,u,g,e,bb,1.585,t,f,0,t,s,420.0,0,0\nb,34.83,4.0,u,g,d,bb,12.5,t,f,0,t,g,0.0,0,0\na,38.58,5.0,u,g,cc,v,13.5,t,f,0,t,g,980.0,0,0\nb,44.25,0.5,u,g,m,v,10.75,t,f,0,f,s,400.0,0,0\nb,44.83,7.0,y,p,c,v,1.625,f,f,0,f,g,160.0,2,0\nb,20.67,5.29,u,g,q,v,0.375,t,t,1,f,g,160.0,0,0\nb,34.08,6.5,u,g,aa,v,0.125,t,f,0,t,g,443.0,0,0\na,19.17,0.585,y,p,aa,v,0.585,t,f,0,t,g,160.0,0,0\nb,21.67,1.165,y,p,k,v,2.5,t,t,1,f,g,180.0,20,0\nb,21.5,9.75,u,g,c,v,0.25,t,f,0,f,g,140.0,0,0\nb,49.58,19.0,u,g,ff,ff,0.0,t,t,1,f,g,94.0,0,0\na,27.67,1.5,u,g,m,v,2.0,t,f,0,f,s,368.0,0,0\nb,39.83,0.5,u,g,m,v,0.25,t,f,0,f,s,288.0,0,0\na,0.0,3.5,u,g,d,v,3.0,t,f,0,t,g,300.0,0,0\nb,27.25,0.625,u,g,aa,v,0.455,t,f,0,t,g,200.0,0,0\nb,37.17,4.0,u,g,c,bb,5.0,t,f,0,t,s,280.0,0,0\nb,0.0,0.375,u,g,d,v,0.875,t,f,0,t,s,928.0,0,0\nb,25.67,2.21,y,p,aa,v,4.0,t,f,0,f,g,188.0,0,0\nb,34.0,4.5,u,g,aa,v,1.0,t,f,0,t,g,240.0,0,0\na,49.0,1.5,u,g,j,j,0.0,t,f,0,t,g,100.0,27,0\nb,62.5,12.75,y,p,c,h,5.0,t,f,0,f,g,112.0,0,0\nb,31.42,15.5,u,g,c,v,0.5,t,f,0,f,g,120.0,0,0\nb,0.0,5.0,y,p,aa,v,8.5,t,f,0,f,g,0.0,0,0\nb,52.33,1.375,y,p,c,h,9.46,t,f,0,t,g,200.0,100,0\nb,28.75,1.5,y,p,c,v,1.5,t,f,0,t,g,0.0,225,0\na,28.58,3.54,u,g,i,bb,0.5,t,f,0,t,g,171.0,0,0\nb,23.0,0.625,y,p,aa,v,0.125,t,f,0,f,g,180.0,1,0\nb,0.0,0.5,u,g,c,bb,0.835,t,f,0,t,s,320.0,0,0\na,22.5,11.0,y,p,q,v,3.0,t,f,0,t,g,268.0,0,0\na,28.5,1.0,u,g,q,v,1.0,t,t,2,t,g,167.0,500,0\nb,37.5,1.75,y,p,c,bb,0.25,t,f,0,t,g,164.0,400,0\nb,35.25,16.5,y,p,c,v,4.0,t,f,0,f,g,80.0,0,0\nb,18.67,5.0,u,g,q,v,0.375,t,t,2,f,g,0.0,38,0\nb,25.0,12.0,u,g,k,v,2.25,t,t,2,t,g,120.0,5,0\nb,27.83,4.0,y,p,i,h,5.75,t,t,2,t,g,75.0,0,0\nb,54.83,15.5,u,g,e,z,0.0,t,t,20,f,g,152.0,130,0\nb,28.75,1.165,u,g,k,v,0.5,t,f,0,f,s,280.0,0,0\na,25.0,11.0,y,p,aa,v,4.5,t,f,0,f,g,120.0,0,0\nb,40.92,2.25,y,p,x,h,10.0,t,f,0,t,g,176.0,0,0\na,19.75,0.75,u,g,c,v,0.795,t,t,5,t,g,140.0,5,0\nb,29.17,3.5,u,g,w,v,3.5,t,t,3,t,g,329.0,0,0\na,24.5,1.04,y,p,ff,ff,0.5,t,t,3,f,g,180.0,147,0\nb,24.58,12.5,u,g,w,v,0.875,t,f,0,t,g,260.0,0,0\na,33.75,0.75,u,g,k,bb,1.0,t,t,3,t,g,212.0,0,0\nb,20.67,1.25,y,p,c,h,1.375,t,t,3,t,g,140.0,210,0\na,25.42,1.125,u,g,q,v,1.29,t,t,2,f,g,200.0,0,0\nb,37.75,7.0,u,g,q,h,11.5,t,t,7,t,g,300.0,5,0\nb,52.5,6.5,u,g,k,v,6.29,t,t,15,f,g,0.0,11202,1\nb,57.83,7.04,u,g,m,v,14.0,t,t,6,t,g,360.0,1332,1\na,20.75,10.335,u,g,cc,h,0.335,t,t,1,t,g,80.0,50,1\nb,39.92,6.21,u,g,q,v,0.04,t,t,1,f,g,200.0,300,1\nb,25.67,12.5,u,g,cc,v,1.21,t,t,67,t,g,140.0,258,1\na,24.75,12.5,u,g,aa,v,1.5,t,t,12,t,g,120.0,567,1\na,44.17,6.665,u,g,q,v,7.375,t,t,3,t,g,0.0,0,1\na,23.5,9.0,u,g,q,v,8.5,t,t,5,t,g,120.0,0,1\nb,34.92,5.0,u,g,x,h,7.5,t,t,6,t,g,0.0,1000,1\nb,47.67,2.5,u,g,m,bb,2.5,t,t,12,t,g,410.0,2510,1\nb,22.75,11.0,u,g,q,v,2.5,t,t,7,t,g,100.0,809,1\nb,34.42,4.25,u,g,i,bb,3.25,t,t,2,f,g,274.0,610,1\na,28.42,3.5,u,g,w,v,0.835,t,f,0,f,s,280.0,0,1\nb,67.75,5.5,u,g,e,z,13.0,t,t,1,t,g,0.0,0,1\nb,20.42,1.835,u,g,c,v,2.25,t,t,1,f,g,100.0,150,1\na,47.42,8.0,u,g,e,bb,6.5,t,t,6,f,g,375.0,51100,1\nb,36.25,5.0,u,g,c,bb,2.5,t,t,6,f,g,0.0,367,1\nb,32.67,5.5,u,g,q,h,5.5,t,t,12,t,g,408.0,1000,1\nb,48.58,6.5,u,g,q,h,6.0,t,f,0,t,g,350.0,0,1\nb,39.92,0.54,y,p,aa,v,0.5,t,t,3,f,g,200.0,1000,1\nb,33.58,2.75,u,g,m,v,4.25,t,t,6,f,g,204.0,0,1\na,18.83,9.5,u,g,w,v,1.625,t,t,6,t,g,40.0,600,1\na,26.92,13.5,u,g,q,h,5.0,t,t,2,f,g,0.0,5000,1\na,31.25,3.75,u,g,cc,h,0.625,t,t,9,t,g,181.0,0,1\na,56.5,16.0,u,g,j,ff,0.0,t,t,15,f,g,0.0,247,1\nb,43.0,0.29,y,p,cc,h,1.75,t,t,8,f,g,100.0,375,1\nb,22.33,11.0,u,g,w,v,2.0,t,t,1,f,g,80.0,278,1\nb,27.25,1.665,u,g,cc,h,5.085,t,t,9,f,g,399.0,827,1\nb,32.83,2.5,u,g,cc,h,2.75,t,t,6,f,g,160.0,2072,1\nb,23.25,1.5,u,g,q,v,2.375,t,t,3,t,g,0.0,582,1\na,40.33,7.54,y,p,q,h,8.0,t,t,14,f,g,0.0,2300,1\na,30.5,6.5,u,g,c,bb,4.0,t,t,7,t,g,0.0,3065,1\na,52.83,15.0,u,g,c,v,5.5,t,t,14,f,g,0.0,2200,1\na,46.67,0.46,u,g,cc,h,0.415,t,t,11,t,g,440.0,6,1\na,58.33,10.0,u,g,q,v,4.0,t,t,14,f,g,0.0,1602,1\nb,37.33,6.5,u,g,m,h,4.25,t,t,12,t,g,93.0,0,1\nb,23.08,2.5,u,g,c,v,1.085,t,t,11,t,g,60.0,2184,1\nb,32.75,1.5,u,g,cc,h,5.5,t,t,3,t,g,0.0,0,1\na,21.67,11.5,y,p,j,j,0.0,t,t,11,t,g,0.0,0,1\na,28.5,3.04,y,p,x,h,2.54,t,t,1,f,g,70.0,0,1\na,68.67,15.0,u,g,e,z,0.0,t,t,14,f,g,0.0,3376,1\nb,28.0,2.0,u,g,k,h,4.165,t,t,2,t,g,181.0,0,1\nb,34.08,0.08,y,p,m,bb,0.04,t,t,1,t,g,280.0,2000,1\nb,27.67,2.0,u,g,x,h,1.0,t,t,4,f,g,140.0,7544,1\nb,44.0,2.0,u,g,m,v,1.75,t,t,2,t,g,0.0,15,1\nb,25.08,1.71,u,g,x,v,1.665,t,t,1,t,g,395.0,20,1\nb,32.0,1.75,y,p,e,h,0.04,t,f,0,t,g,393.0,0,1\na,60.58,16.5,u,g,q,v,11.0,t,f,0,t,g,21.0,10561,1\na,40.83,10.0,u,g,q,h,1.75,t,f,0,f,g,29.0,837,1\nb,19.33,9.5,u,g,q,v,1.0,t,f,0,t,g,60.0,400,1\na,32.33,0.54,u,g,cc,v,0.04,t,f,0,f,g,440.0,11177,1\nb,36.67,3.25,u,g,q,h,9.0,t,f,0,t,g,102.0,639,1\nb,37.5,1.125,y,p,d,v,1.5,f,f,0,t,g,431.0,0,1\na,25.08,2.54,y,p,aa,v,0.25,t,f,0,t,g,370.0,0,1\nb,41.33,0.0,u,g,c,bb,15.0,t,f,0,f,g,0.0,0,1\nb,56.0,12.5,u,g,k,h,8.0,t,f,0,t,g,24.0,2028,1\na,49.83,13.585,u,g,k,h,8.5,t,f,0,t,g,0.0,0,1\nb,22.67,10.5,u,g,q,h,1.335,t,f,0,f,g,100.0,0,1\nb,27.0,1.5,y,p,w,v,0.375,t,f,0,t,g,260.0,1065,1\nb,25.0,12.5,u,g,aa,v,3.0,t,f,0,t,s,20.0,0,1\na,26.08,8.665,u,g,aa,v,1.415,t,f,0,f,g,160.0,150,1\na,18.42,9.25,u,g,q,v,1.21,t,t,4,f,g,60.0,540,1\nb,20.17,8.17,u,g,aa,v,1.96,t,t,14,f,g,60.0,158,1\nb,47.67,0.29,u,g,c,bb,15.0,t,t,20,f,g,0.0,15000,1\na,21.25,2.335,u,g,i,bb,0.5,t,t,4,f,s,80.0,0,1\na,20.67,3.0,u,g,q,v,0.165,t,t,3,f,g,100.0,6,1\na,57.08,19.5,u,g,c,v,5.5,t,t,7,f,g,0.0,3000,1\na,22.42,5.665,u,g,q,v,2.585,t,t,7,f,g,129.0,3257,1\nb,48.75,8.5,u,g,c,h,12.5,t,t,9,f,g,181.0,1655,1\nb,40.0,6.5,u,g,aa,bb,3.5,t,t,1,f,g,0.0,500,1\nb,40.58,5.0,u,g,c,v,5.0,t,t,7,f,g,0.0,3065,1\na,28.67,1.04,u,g,c,v,2.5,t,t,5,t,g,300.0,1430,1\na,33.08,4.625,u,g,q,h,1.625,t,t,2,f,g,0.0,0,1\nb,21.33,10.5,u,g,c,v,3.0,t,f,0,t,g,0.0,0,1\nb,42.0,0.205,u,g,i,h,5.125,t,f,0,f,g,400.0,0,1\nb,41.75,0.96,u,g,x,v,2.5,t,f,0,f,g,510.0,600,1\nb,22.67,1.585,y,p,w,v,3.085,t,t,6,f,g,80.0,0,1\nb,34.5,4.04,y,p,i,bb,8.5,t,t,7,t,g,195.0,0,1\nb,28.25,5.04,y,p,c,bb,1.5,t,t,8,t,g,144.0,7,1\nb,33.17,3.165,y,p,x,v,3.165,t,t,3,t,g,380.0,0,1\nb,48.17,7.625,u,g,w,h,15.5,t,t,12,f,g,0.0,790,1\nb,27.58,2.04,y,p,aa,v,2.0,t,t,3,t,g,370.0,560,1\nb,22.58,10.04,u,g,x,v,0.04,t,t,9,f,g,60.0,396,1\na,24.08,0.5,u,g,q,h,1.25,t,t,1,f,g,0.0,678,1\na,41.33,1.0,u,g,i,bb,2.25,t,f,0,t,g,0.0,300,1\nb,24.83,2.75,u,g,c,v,2.25,t,t,6,f,g,0.0,600,1\na,20.75,10.25,u,g,q,v,0.71,t,t,2,t,g,49.0,0,1\nb,36.33,2.125,y,p,w,v,0.085,t,t,1,f,g,50.0,1187,1\na,35.42,12.0,u,g,q,h,14.0,t,t,8,f,g,0.0,6590,1\na,71.58,0.0,Missing,Missing,Missing,Missing,0.0,f,f,0,f,p,0.0,0,1\nb,28.67,9.335,u,g,q,h,5.665,t,t,6,f,g,381.0,168,1\nb,35.17,2.5,u,g,k,v,4.5,t,t,7,f,g,150.0,1270,1\nb,39.5,4.25,u,g,c,bb,6.5,t,t,16,f,g,117.0,1210,1\nb,39.33,5.875,u,g,cc,h,10.0,t,t,14,t,g,399.0,0,1\nb,24.33,6.625,y,p,d,v,5.5,t,f,0,t,s,100.0,0,1\nb,60.08,14.5,u,g,ff,ff,18.0,t,t,15,t,g,0.0,1000,1\nb,23.08,11.5,u,g,i,v,3.5,t,t,9,f,g,56.0,742,1\nb,26.67,2.71,y,p,cc,v,5.25,t,t,1,f,g,211.0,0,1\nb,48.17,3.5,u,g,aa,v,3.5,t,f,0,f,s,230.0,0,1\nb,41.17,4.04,u,g,cc,h,7.0,t,t,8,f,g,320.0,0,1\nb,55.92,11.5,u,g,ff,ff,5.0,t,t,5,f,g,0.0,8851,1\nb,53.92,9.625,u,g,e,v,8.665,t,t,5,f,g,0.0,0,1\na,18.92,9.25,y,p,c,v,1.0,t,t,4,t,g,80.0,500,1\na,50.08,12.54,u,g,aa,v,2.29,t,t,3,t,g,156.0,0,1\nb,65.42,11.0,u,g,e,z,20.0,t,t,7,t,g,22.0,0,1\na,17.58,9.0,u,g,aa,v,1.375,t,f,0,t,g,0.0,0,1\na,18.83,9.54,u,g,aa,v,0.085,t,f,0,f,g,100.0,0,1\na,37.75,5.5,u,g,q,v,0.125,t,f,0,t,g,228.0,0,1\nb,23.25,4.0,u,g,c,bb,0.25,t,f,0,t,g,160.0,0,1\nb,18.08,5.5,u,g,k,v,0.5,t,f,0,f,g,80.0,0,1\na,22.5,8.46,y,p,x,v,2.46,f,f,0,f,g,164.0,0,1\nb,19.67,0.375,u,g,q,v,2.0,t,t,2,t,g,80.0,0,1\nb,22.08,11.0,u,g,cc,v,0.665,t,f,0,f,g,100.0,0,1\nb,25.17,3.5,u,g,cc,v,0.625,t,t,7,f,g,0.0,7059,1\na,47.42,3.0,u,g,x,v,13.875,t,t,2,t,g,519.0,1704,1\nb,33.5,1.75,u,g,x,h,4.5,t,t,4,t,g,253.0,857,1\nb,27.67,13.75,u,g,w,v,5.75,t,f,0,t,g,487.0,500,1\na,58.42,21.0,u,g,i,bb,10.0,t,t,13,f,g,0.0,6700,1\na,20.67,1.835,u,g,q,v,2.085,t,t,5,f,g,220.0,2503,1\nb,26.17,0.25,u,g,i,bb,0.0,t,f,0,t,g,0.0,0,1\nb,21.33,7.5,u,g,aa,v,1.415,t,t,1,f,g,80.0,9800,1\nb,42.83,4.625,u,g,q,v,4.58,t,f,0,f,s,0.0,0,1\nb,38.17,10.125,u,g,x,v,2.5,t,t,6,f,g,520.0,196,1\nb,20.5,10.0,y,p,c,v,2.5,t,f,0,f,s,40.0,0,1\nb,48.25,25.085,u,g,w,v,1.75,t,t,3,f,g,120.0,14,1\nb,28.33,5.0,u,g,w,v,11.0,t,f,0,t,g,70.0,0,1\na,18.75,7.5,u,g,q,v,2.71,t,t,5,f,g,0.0,26726,1\nb,18.5,2.0,u,g,i,v,1.5,t,t,2,f,g,120.0,300,1\nb,33.17,3.04,y,p,c,h,2.04,t,t,1,t,g,180.0,18027,1\nb,45.0,8.5,u,g,cc,h,14.0,t,t,1,t,g,88.0,2000,1\na,19.67,0.21,u,g,q,h,0.29,t,t,11,f,g,80.0,99,1\nMissing,24.5,12.75,u,g,c,bb,4.75,t,t,2,f,g,73.0,444,1\nb,21.83,11.0,u,g,x,v,0.29,t,t,6,f,g,121.0,0,1\nb,40.25,21.5,u,g,e,z,20.0,t,t,11,f,g,0.0,1200,1\nb,41.42,5.0,u,g,q,h,5.0,t,t,6,t,g,470.0,0,1\na,17.83,11.0,u,g,x,h,1.0,t,t,11,f,g,0.0,3000,1\nb,23.17,11.125,u,g,x,h,0.46,t,t,1,f,g,100.0,0,1\nb,0.0,0.625,u,g,k,v,0.25,f,f,0,f,g,380.0,2010,0\nb,18.17,10.25,u,g,c,h,1.085,f,f,0,f,g,320.0,13,0\nb,20.0,11.045,u,g,c,v,2.0,f,f,0,t,g,136.0,0,0\nb,20.0,0.0,u,g,d,v,0.5,f,f,0,f,g,144.0,0,0\na,20.75,9.54,u,g,i,v,0.04,f,f,0,f,g,200.0,1000,0\na,24.5,1.75,y,p,c,v,0.165,f,f,0,f,g,132.0,0,0\nb,32.75,2.335,u,g,d,h,5.75,f,f,0,t,g,292.0,0,0\na,52.17,0.0,y,p,ff,ff,0.0,f,f,0,f,g,0.0,0,0\na,48.17,1.335,u,g,i,o,0.335,f,f,0,f,g,0.0,120,0\na,20.42,10.5,y,p,x,h,0.0,f,f,0,t,g,154.0,32,0\nb,50.75,0.585,u,g,ff,ff,0.0,f,f,0,f,g,145.0,0,0\nb,17.08,0.085,y,p,c,v,0.04,f,f,0,f,g,140.0,722,0\nb,18.33,1.21,y,p,e,dd,0.0,f,f,0,f,g,100.0,0,0\na,32.0,6.0,u,g,d,v,1.25,f,f,0,f,g,272.0,0,0\nb,59.67,1.54,u,g,q,v,0.125,t,f,0,t,g,260.0,0,1\nb,18.0,0.165,u,g,q,n,0.21,f,f,0,f,g,200.0,40,1\nb,37.58,0.0,Missing,Missing,Missing,Missing,0.0,f,f,0,f,p,0.0,0,1\nb,32.33,2.5,u,g,c,v,1.25,f,f,0,t,g,280.0,0,0\nb,18.08,6.75,y,p,m,v,0.04,f,f,0,f,g,140.0,0,0\nb,38.25,10.125,y,p,k,v,0.125,f,f,0,f,g,160.0,0,0\nb,30.67,2.5,u,g,cc,h,2.25,f,f,0,t,s,340.0,0,0\nb,18.58,5.71,u,g,d,v,0.54,f,f,0,f,g,120.0,0,0\na,19.17,5.415,u,g,i,h,0.29,f,f,0,f,g,80.0,484,0\na,18.17,10.0,y,p,q,h,0.165,f,f,0,f,g,340.0,0,0\nb,24.58,13.5,y,p,ff,ff,0.0,f,f,0,f,g,0.0,0,0\nb,16.25,0.835,u,g,m,v,0.085,t,f,0,f,s,200.0,0,0\nb,21.17,0.875,y,p,c,h,0.25,f,f,0,f,g,280.0,204,0\nb,23.92,0.585,y,p,cc,h,0.125,f,f,0,f,g,240.0,1,0\nb,17.67,4.46,u,g,c,v,0.25,f,f,0,f,s,80.0,0,0\na,16.5,1.25,u,g,q,v,0.25,f,t,1,f,g,108.0,98,0\nb,23.25,12.625,u,g,c,v,0.125,f,t,2,f,g,0.0,5552,0\nb,17.58,10.0,u,g,w,h,0.165,f,t,1,f,g,120.0,1,0\na,0.0,1.5,u,g,ff,ff,0.0,f,t,2,t,g,200.0,105,0\nb,29.5,0.58,u,g,w,v,0.29,f,t,1,f,g,340.0,2803,0\nb,18.83,0.415,y,p,c,v,0.165,f,t,1,f,g,200.0,1,0\na,21.75,1.75,y,p,j,j,0.0,f,f,0,f,g,160.0,0,0\nb,23.0,0.75,u,g,m,v,0.5,f,f,0,t,s,320.0,0,0\na,18.25,10.0,u,g,w,v,1.0,f,t,1,f,g,120.0,1,0\nb,25.42,0.54,u,g,w,v,0.165,f,t,1,f,g,272.0,444,0\nb,35.75,2.415,u,g,w,v,0.125,f,t,2,f,g,220.0,1,0\na,16.08,0.335,u,g,ff,ff,0.0,f,t,1,f,g,160.0,126,0\na,31.92,3.125,u,g,ff,ff,3.04,f,t,2,t,g,200.0,4,0\nb,69.17,9.0,u,g,ff,ff,4.0,f,t,1,f,g,70.0,6,0\nb,32.92,2.5,u,g,aa,v,1.75,f,t,2,t,g,720.0,0,0\nb,16.33,2.75,u,g,aa,v,0.665,f,t,1,f,g,80.0,21,0\nb,22.17,12.125,u,g,c,v,3.335,f,t,2,t,g,180.0,173,0\na,57.58,2.0,u,g,ff,ff,6.5,f,t,1,f,g,0.0,10,0\nb,18.25,0.165,u,g,d,v,0.25,f,f,0,t,s,280.0,0,0\nb,23.42,1.0,u,g,c,v,0.5,f,f,0,t,s,280.0,0,0\na,15.92,2.875,u,g,q,v,0.085,f,f,0,f,g,120.0,0,0\na,24.75,13.665,u,g,q,h,1.5,f,f,0,f,g,280.0,1,0\nb,48.75,26.335,y,p,ff,ff,0.0,t,f,0,t,g,0.0,0,0\nb,23.5,2.75,u,g,ff,ff,4.5,f,f,0,f,g,160.0,25,0\nb,18.58,10.29,u,g,ff,ff,0.415,f,f,0,f,g,80.0,0,0\nb,27.75,1.29,u,g,k,h,0.25,f,f,0,t,s,140.0,0,0\na,31.75,3.0,y,p,j,j,0.0,f,f,0,f,g,160.0,20,0\na,24.83,4.5,u,g,w,v,1.0,f,f,0,t,g,360.0,6,0\nb,19.0,1.75,y,p,c,v,2.335,f,f,0,t,g,112.0,6,0\na,16.33,0.21,u,g,aa,v,0.125,f,f,0,f,g,200.0,1,0\na,18.58,10.0,u,g,d,v,0.415,f,f,0,f,g,80.0,42,0\nb,16.25,0.0,y,p,aa,v,0.25,f,f,0,f,g,60.0,0,0\nb,23.0,0.75,u,g,m,v,0.5,t,f,0,t,s,320.0,0,0\nb,21.17,0.25,y,p,c,h,0.25,f,f,0,f,g,280.0,204,0\nb,17.5,22.0,l,gg,ff,o,0.0,f,f,0,t,p,450.0,100000,1\nb,19.17,0.0,y,p,m,bb,0.0,f,f,0,t,s,500.0,1,1\nb,36.75,0.125,y,p,c,v,1.5,f,f,0,t,g,232.0,113,1\nb,21.25,1.5,u,g,w,v,1.5,f,f,0,f,g,150.0,8,1\na,18.08,0.375,l,gg,cc,ff,10.0,f,f,0,t,s,300.0,0,1\na,33.67,0.375,u,g,cc,v,0.375,f,f,0,f,g,300.0,44,1\nb,48.58,0.205,y,p,k,v,0.25,t,t,11,f,g,380.0,2732,1\nb,33.67,1.25,u,g,w,v,1.165,f,f,0,f,g,120.0,0,0\na,29.5,1.085,y,p,x,v,1.0,f,f,0,f,g,280.0,13,0\nb,30.17,1.085,y,p,c,v,0.04,f,f,0,f,g,170.0,179,0\nMissing,40.83,3.5,u,g,i,bb,0.5,f,f,0,f,s,1160.0,0,0\nb,34.83,2.5,y,p,w,v,3.0,f,f,0,f,s,200.0,0,0\nb,0.0,4.0,y,p,i,v,0.085,f,f,0,t,g,411.0,0,0\nb,20.42,0.0,Missing,Missing,Missing,Missing,0.0,f,f,0,f,p,0.0,0,0\na,33.25,2.5,y,p,c,v,2.5,f,f,0,t,g,0.0,2,0\nb,34.08,2.5,u,g,c,v,1.0,f,f,0,f,g,460.0,16,0\na,25.25,12.5,u,g,d,v,1.0,f,f,0,t,g,180.0,1062,0\nb,34.75,2.5,u,g,cc,bb,0.5,f,f,0,f,g,348.0,0,0\nb,27.67,0.75,u,g,q,h,0.165,f,f,0,t,g,220.0,251,0\nb,47.33,6.5,u,g,c,v,1.0,f,f,0,t,g,0.0,228,0\na,34.83,1.25,y,p,i,h,0.5,f,f,0,t,g,160.0,0,0\na,33.25,3.0,y,p,aa,v,2.0,f,f,0,f,g,180.0,0,0\nb,28.0,3.0,u,g,w,v,0.75,f,f,0,t,g,300.0,67,0\na,39.08,4.0,u,g,c,v,3.0,f,f,0,f,g,480.0,0,0\nb,42.75,4.085,u,g,aa,v,0.04,f,f,0,f,g,108.0,100,0\nb,26.92,2.25,u,g,i,bb,0.5,f,f,0,t,g,640.0,4000,0\nb,33.75,2.75,u,g,i,bb,0.0,f,f,0,f,g,180.0,0,0\nb,38.92,1.75,u,g,k,v,0.5,f,f,0,t,g,300.0,2,0\nb,62.75,7.0,u,g,e,z,0.0,f,f,0,f,g,0.0,12,0\nMissing,32.25,1.5,u,g,c,v,0.25,f,f,0,t,g,372.0,122,0\nb,26.75,4.5,y,p,c,bb,2.5,f,f,0,f,g,200.0,1210,0\nb,63.33,0.54,u,g,c,v,0.585,t,t,3,t,g,180.0,0,0\nb,27.83,1.5,u,g,w,v,2.25,f,t,1,t,g,100.0,3,0\na,26.17,2.0,u,g,j,j,0.0,f,f,0,t,g,276.0,1,0\nb,22.17,0.585,y,p,ff,ff,0.0,f,f,0,f,g,100.0,0,0\nb,22.5,11.5,y,p,m,v,1.5,f,f,0,t,g,0.0,4000,0\nb,30.75,1.585,u,g,d,v,0.585,f,f,0,t,s,0.0,0,0\nb,36.67,2.0,u,g,i,v,0.25,f,f,0,t,g,221.0,0,0\na,16.0,0.165,u,g,aa,v,1.0,f,t,2,t,g,320.0,1,0\nb,41.17,1.335,u,g,d,v,0.165,f,f,0,f,g,168.0,0,0\na,19.5,0.165,u,g,q,v,0.04,f,f,0,t,g,380.0,0,0\nb,32.42,3.0,u,g,d,v,0.165,f,f,0,t,g,120.0,0,0\na,36.75,4.71,u,g,ff,ff,0.0,f,f,0,f,g,160.0,0,0\na,30.25,5.5,u,g,k,v,5.5,f,f,0,t,s,100.0,0,0\nb,23.08,2.5,u,g,ff,ff,0.085,f,f,0,t,g,100.0,4208,0\nb,26.83,0.54,u,g,k,ff,0.0,f,f,0,f,g,100.0,0,0\nb,16.92,0.335,y,p,k,v,0.29,f,f,0,f,s,200.0,0,0\nb,24.42,2.0,u,g,e,dd,0.165,f,t,2,f,g,320.0,1300,0\nb,42.83,1.25,u,g,m,v,13.875,f,t,1,t,g,352.0,112,0\na,22.75,6.165,u,g,aa,v,0.165,f,f,0,f,g,220.0,1000,0\nb,39.42,1.71,y,p,m,v,0.165,f,f,0,f,s,400.0,0,0\na,23.58,11.5,y,p,k,h,3.0,f,f,0,t,g,20.0,16,0\nb,21.42,0.75,y,p,r,n,0.75,f,f,0,t,g,132.0,2,0\nb,33.0,2.5,y,p,w,v,7.0,f,f,0,t,g,280.0,0,0\nb,26.33,13.0,u,g,e,dd,0.0,f,f,0,t,g,140.0,1110,0\na,45.0,4.585,u,g,k,h,1.0,f,f,0,t,s,240.0,0,0\nb,26.25,1.54,u,g,w,v,0.125,f,f,0,f,g,100.0,0,0\nMissing,28.17,0.585,u,g,aa,v,0.04,f,f,0,f,g,260.0,1004,0\na,20.83,0.5,y,p,e,dd,1.0,f,f,0,f,g,260.0,0,0\nb,28.67,14.5,u,g,d,v,0.125,f,f,0,f,g,0.0,286,0\nb,20.67,0.835,y,p,c,v,2.0,f,f,0,t,s,240.0,0,0\nb,34.42,1.335,u,g,i,bb,0.125,f,f,0,t,g,440.0,4500,0\nb,33.58,0.25,u,g,i,bb,4.0,f,f,0,t,s,420.0,0,0\nb,43.17,5.0,u,g,i,bb,2.25,f,f,0,t,g,141.0,0,0\na,22.67,7.0,u,g,c,v,0.165,f,f,0,f,g,160.0,0,0\na,24.33,2.5,y,p,i,bb,4.5,f,f,0,f,g,200.0,456,0\na,56.83,4.25,y,p,ff,ff,5.0,f,f,0,t,g,0.0,4,0\nb,22.08,11.46,u,g,k,v,1.585,f,f,0,t,g,100.0,1212,0\nb,34.0,5.5,y,p,c,v,1.5,f,f,0,t,g,60.0,0,0\nb,22.58,1.5,y,p,aa,v,0.54,f,f,0,t,g,120.0,67,0\nb,21.17,0.0,u,g,c,v,0.5,f,f,0,t,s,0.0,0,0\nb,26.67,14.585,u,g,i,bb,0.0,f,f,0,t,g,178.0,0,0\nb,22.92,0.17,u,g,m,v,0.085,f,f,0,f,s,0.0,0,0\nb,15.17,7.0,u,g,e,v,1.0,f,f,0,f,g,600.0,0,0\nb,39.92,5.0,u,g,i,bb,0.21,f,f,0,f,g,550.0,0,0\nb,27.42,12.5,u,g,aa,bb,0.25,f,f,0,t,g,720.0,0,0\nb,24.75,0.54,u,g,m,v,1.0,f,f,0,t,g,120.0,1,0\nb,41.17,1.25,y,p,w,v,0.25,f,f,0,f,g,0.0,195,0\na,33.08,1.625,u,g,d,v,0.54,f,f,0,t,g,0.0,0,0\nb,29.83,2.04,y,p,x,h,0.04,f,f,0,f,g,128.0,1,0\na,23.58,0.585,y,p,ff,ff,0.125,f,f,0,f,g,120.0,87,0\nb,26.17,12.5,y,p,k,h,1.25,f,f,0,t,g,0.0,17,0\nb,31.0,2.085,u,g,c,v,0.085,f,f,0,f,g,300.0,0,0\nb,20.75,5.085,y,p,j,v,0.29,f,f,0,f,g,140.0,184,0\nb,28.92,0.375,u,g,c,v,0.29,f,f,0,f,g,220.0,140,0\na,51.92,6.5,u,g,i,bb,3.085,f,f,0,t,g,73.0,0,0\na,22.67,0.335,u,g,q,v,0.75,f,f,0,f,s,160.0,0,0\nb,34.0,5.085,y,p,i,bb,1.085,f,f,0,t,g,480.0,0,0\na,69.5,6.0,u,g,ff,ff,0.0,f,f,0,f,s,0.0,0,0\na,40.33,8.125,y,p,k,v,0.165,f,t,2,f,g,0.0,18,0\na,19.58,0.665,y,p,c,v,1.0,f,t,1,f,g,2000.0,2,0\nb,16.0,3.125,u,g,w,v,0.085,f,t,1,f,g,0.0,6,0\nb,17.08,0.25,u,g,q,v,0.335,f,t,4,f,g,160.0,8,0\nb,31.25,2.835,u,g,ff,ff,0.0,f,t,5,f,g,176.0,146,0\nb,25.17,3.0,u,g,c,v,1.25,f,t,1,f,g,0.0,22,0\na,22.67,0.79,u,g,i,v,0.085,f,f,0,f,g,144.0,0,0\nb,40.58,1.5,u,g,i,bb,0.0,f,f,0,f,s,300.0,0,0\nb,22.25,0.46,u,g,k,v,0.125,f,f,0,t,g,280.0,55,0\na,22.25,1.25,y,p,ff,ff,

In [12]:
# Membaca data yang telah di transformasi sebelumnya
data = pd.read_csv('creditApprovalUCI.csv')
data.head()

  A1     A2     A3 A4 A5 A6 A7    A8 A9 A10  A11 A12 A13    A14  A15  A16
0  b  30.83  0.000  u  g  w  v  1.25  t   t    1   f   g  202.0    0    1
1  a  58.67  4.460  u  g  q  h  3.04  t   t    6   f   g   43.0  560    1
2  a  24.50  0.500  u  g  q  h  1.50  t   f    0   f   g  280.0  824    1
3  b  27.83  1.540  u  g  w  v  3.75  t   t    5   t   g  100.0    3    1
4  b  20.17  5.625  u  g  w  v  1.71  t   f    0   f   s  120.0    0    1

In [13]:
# Memisahkan data yang akan digunakan sebagai testing ste
X_train, X_test, y_train, y_test = train_test_split( data.drop(labels=['A16'], axis=1), data['A16'], test_size=0.3,
random_state=0)

In [14]:
#Melakukan pengecekan nilai apa saja yang ada pada kolom A4
X_train['A4'].unique()

array(['u', 'y', 'Missing', 'l'], dtype=object)

In [15]:
tmp = pd.get_dummies(X_train['A4'], drop_first=True)

# Menampilkan 5 data awal dari hasil transformasi yang dilakukan
tmp.head()

         l      u      y
596  False   True  False
303  False   True  False
204  False  False   True
351  False  False   True
118  False   True  False

In [16]:
# Untuk melakukan proses encoding data kategori secara bersamaan, pertama-tama kita membentuk list dari masing-masing
# kolom
vars_categorical = ['A1', 'A4', 'A5', 'A6', 'A7', 'A9', 'A10', 'A12', 'A13']

In [17]:
# Melaukan encoding pada dataset training dan testing pada fitur / kolom yang telah di definisikan sebelumnya.
# Fungsi get_dummies() panda menangkap nama variabel, katakanlah, A1,
# dan menempatkan garis bawah diikuti dengan nama kategori untuk mengidentifikasi variabel biner yang dihasilkan.
X_train_enc = pd.get_dummies(X_train[vars_categorical], drop_first=True)
X_test_enc = pd.get_dummies(X_test[vars_categorical], drop_first=True)

In [18]:
X_train_enc.head()

,A1_a,A1_b,A4_l,A4_u,A4_y,A5_g,A5_gg,A5_p,A6_aa,A6_c,...,A7_j,A7_n,A7_o,A7_v,A7_z,A9_t,A10_t,A12_t,A13_p,A13_s
596,True,False,False,True,False,True,False,False,False,True,...,False,False,False,True,False,True,True,True,False,False
303,True,False,False,True,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
204,False,True,False,False,True,False,False,True,False,False,...,False,False,False,True,False,True,True,False,False,False
351,False,True,False,False,True,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
118,False,True,False,True,False,True,False,False,False,False,...,False,False,False,True,False,True,True,True,False,False

In [20]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(
    categories='auto',
    drop='first',
    sparse_output=False
)

In [22]:
encoder.fit(X_train[vars_categorical])

OneHotEncoder(drop='first', sparse_output=False)

In [23]:
X_train_enc = encoder.transform(X_train[vars_categorical])
X_test_enc = encoder.transform(X_test[vars_categorical])

In [25]:
!pip install feature-engine

Collecting feature-engine
  Downloading feature_engine-1.9.4-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy>=1.18.2 in /usr/local/lib/python3.12/dist-packages (from feature-engine) (2.0.2)
Requirement already satisfied: pandas>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from feature-engine) (2.2.2)
Requirement already satisfied: scikit-learn>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from feature-engine) (1.6.1)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from feature-engine) (1.16.3)
Requirement already satisfied: statsmodels>=0.11.1 in /usr/local/lib/python3.12/dist-packages (from feature-engine) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->feature-engine) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->feature-engine) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.2.0->feature-engine) (2026.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4.0->feature-engine) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.4.0->feature-engine) (3.6.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.11.1->feature-engine) (1.0.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.11.1->feature-engine) (26.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->feature-engine) (1.17.0)
Downloading feature_engine-1.9.4-py3-none-any.whl (243 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 243.5/243.5 kB 8.3 MB/s eta 0:00:00
Installing collected packages: feature-engine
Successfully installed feature-engine-1.9.4

In [26]:
## jangan lupa melakukan instalasi feature_engine terlebih dahulu dengan perintah : pip install feature_engine dan pip install feature-engine==0.3.0

from feature_engine.encoding import OneHotEncoder

In [28]:
# set up encoder untuk membentuk nilai k-1
# Parameter top_categories=None, menunjukkan bahwa Anda akan melakukan encoding semua pada
# kategori yang ada dalam variabel kategori.
from feature_engine.encoding import OneHotEncoder

ohe_enc = OneHotEncoder(
    top_categories=None,
    drop_last=True
)

In [29]:
# Implementasi encoder ke rlata latih sehingga ia mempelajari kategori dan variabel yang akan dikodekan:
ohe_enc.fit(X_train)

/usr/local/lib/python3.12/dist-packages/feature_engine/variable_handling/_variable_type_checks.py:34: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  var = pd.to_datetime(column, utc=True)
/usr/local/lib/python3.12/dist-packages/feature_engine/variable_handling/_variable_type_checks.py:34: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  var = pd.to_datetime(column, utc=True)
/usr/local/lib/python3.12/dist-packages/feature_engine/variable_handling/_variable_type_checks.py:34: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  var = pd.to_datetime(column, utc=True)
/usr/local/lib/python3.12/dist-packages/feature_engine/variable_handling/_variable_type_checks.py:34: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  var = pd.to_datetime(column, utc=True)
/usr/local/lib/python3.12/dist-packages/feature_engine/variable_handling/_variable_type_checks.py:34: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  var = pd.to_datetime(column, utc=True)
/usr/local/lib/python3.12/dist-packages/feature_engine/variable_handling/_variable_type_checks.py:34: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  var = pd.to_datetime(column, utc=True)
/usr/local/lib/python3.12/dist-packages/feature_engine/variable_handling/_variable_type_checks.py:34: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  var = pd.to_datetime(column, utc=True)
/usr/local/lib/python3.12/dist-packages/feature_engine/variable_handling/_variable_type_checks.py:34: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  var = pd.to_datetime(column, utc=True)
/usr/local/lib/python3.12/dist-packages/feature_engine/variable_handling/_variable_type_checks.py:34: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  var = pd.to_datetime(column, utc=True)

OneHotEncoder(drop_last=True)

In [30]:
X_train_enc = ohe_enc.transform(X_train)
X_test_enc = ohe_enc.transform(X_test)
X_train.head()

    A1     A2     A3 A4 A5  A6  A7      A8 A9 A10  A11 A12 A13    A14   A15
596  a  46.08  3.000  u  g   c   v   2.375  t   t    8   t   g  396.0  4159
303  a  15.92  2.875  u  g   q   v   0.085  f   f    0   f   g  120.0     0
204  b  36.33  2.125  y  p   w   v   0.085  t   t    1   f   g   50.0  1187
351  b  22.17  0.585  y  p  ff  ff   0.000  f   f    0   f   g  100.0     0
118  b  57.83  7.040  u  g   m   v  14.000  t   t    6   t   g  360.0  1332

In [31]:
X_train_enc.head()

,A2,A3,A8,A11,A14,A15,A1_a,A1_b,A4_u,A4_y,...,A7_z,A7_bb,A7_j,A7_Missing,A7_n,A9_t,A10_t,A12_t,A13_g,A13_s
596,46.08,3.000,2.375,8,396.0,4159,1,0,1,0,...,0,0,0,0,0,1,1,1,1,0
303,15.92,2.875,0.085,0,120.0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,1,0
204,36.33,2.125,0.085,1,50.0,1187,0,1,0,1,...,0,0,0,0,0,1,1,0,1,0
351,22.17,0.585,0.000,0,100.0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,1,0
118,57.83,7.040,14.000,6,360.0,1332,0,1,1,0,...,0,0,0,0,0,1,1,1,1,0